--[[
    init.lua
    Created: 08/11/2024 14:35:15
    Description: Autogenerated script file for the map TarroForestPassage.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local TarroForestPassage = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroForestPassage.Init(map)
--Engine callback function
function TarroForestPassage.Init(map)
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  if outside_enter == 1 then
    GROUND:TeleportTo(partner, 557, 504, Direction.Left, 0)
  end
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true

  if SV.tarro_town.PieChapter < 3 then
    UI:SetSpeaker(partner)
    GROUND:CharTurnToCharAnimated(azura, maru, 4)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Okay! There should be an apple around here, I'm sure!")
    SV.tarro_town.PieChapter = 3
  end

  if SV.tarro_town.PieChapter >= 5 then -- after dungeon completion
    GROUND:Hide("Cherry")
    GROUND:Hide("BigApple")
  end

  if SV.tarro_town.DarknessChapter == 1 then
    TarroForestPassage.Darkness()
  end
  
end

function TarroForestPassage.Darkness()
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local arama = CH("Arama")
  local amazuru = CH("Amazuru")
  AI:DisableCharacterAI(azura)
  GAME:CutsceneMode(true)

  GROUND:TeleportTo(maru, 80, 500, Direction.Up, 0)
  GROUND:TeleportTo(azura, 120, 510, Direction.Up, 0)

  local coro01 = TASK:BranchCoroutine(function()
    GROUND:MoveToPosition(maru, maru.Position.X, maru.Position.Y - 14, false, 0.4)
    GROUND:CharTurnToCharAnimated(maru, azura, 4)
    end)
  local coro02 = TASK:BranchCoroutine(function()
    GROUND:MoveToPosition(azura, azura.Position.X, azura.Position.Y - 14, false, 0.5)
    GROUND:CharTurnToCharAnimated(azura, maru, 8)
    end)
  local coro03 = TASK:BranchCoroutine(function()
    GAME:FadeIn(120)
    end)
  
  TASK:JoinCoroutines({coro01, coro02, coro03})

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowTimedDialogue("That was fun, now we can go home and", 0)

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Shouting")
  UI:WaitShowDialogue("Waaaaaaaaaaaaaait!")

  local coro1 = TASK:BranchCoroutine(function()
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Huh,[pause=70] mama...?")

    GROUND:CharTurnToCharAnimated(maru, arama, 5)
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("What are you doing here...?")
    end)	
  local coro2 = TASK:BranchCoroutine(function()
    GROUND:MoveToPosition(arama, (maru.Position.X + azura.Position.X) / 2, azura.Position.Y - 50, true, 8)
    end)
  
  TASK:JoinCoroutines({coro1, coro2})

  GROUND:CharTurnToCharAnimated(azura, arama, 8)
  GROUND:CharTurnToCharAnimated(maru, arama, 4)

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("You two can't be here!")

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowTimedDialogue("But mama, we can-...")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("Talking back to me, huh?!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("But...[pause=30] mom...")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I know you two are ready, but I can't let you go...!")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Even if you two have the experience...")

  COMMON.CharSweatdrop("PLAYER")
  GAME:WaitFrames(5)
  COMMON.CharSweatdrop("Teammate1")
  GAME:WaitFrames(5)

  local coro1 = TASK:BranchCoroutine(function()
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("But what kind of mother would I be if I just kept you two stuck here...?")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Difficult decision...")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("You know what,[pause=10] sure! You two can do it!")
    end)	
  local coro2 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(60)
    COMMON.FaceEachother("PLAYER", "Teammate1")
    GAME:WaitFrames(30)
    GROUND:CharTurnToCharAnimated(azura, arama, 8)
    GROUND:CharTurnToCharAnimated(maru, arama, 8)
    end)
  
  TASK:JoinCoroutines({coro1, coro2})

  GROUND:MoveToPosition(arama, arama.Position.X, azura.Position.Y + 20, true, 9)
  GROUND:MoveToPosition(arama, azura.Position.X, azura.Position.Y + 20, true, 9)
  GROUND:CharTurnToCharAnimated(arama, azura, 8)

  local coro001 = TASK:BranchCoroutine(function()
    GROUND:AnimateToPosition(azura, "None", Dir8.Up, 120, 80, 0.5, 2, 0)
    end)	
  local coro002 = TASK:BranchCoroutine(function()
    GROUND:AnimateToPosition(arama, "Walk", Dir8.Up, 120, 100, 5, 2, 0)
    end)
  local coro003 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(40)
    COMMON.CharSweatdrop("PLAYER")
    GAME:WaitFrames(5)
    GROUND:MoveToPosition(maru, maru.Position.X, maru.Position.Y - 400, false, 2)
    GROUND:CharTurnToCharAnimated(maru, arama, 8)
    end)
  local coro004 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(20)
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Surprised")
    UI:WaitShowTimedDialogue("Huh?![pause=15] Hey![pause=15] Y[emote=Angry]ou're pushing,[pause=45] m[emote=Shouting]ama!", 40)

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Mom, what's going on?[pause=30] You're scaring me...")

    UI:SetSpeaker(arama)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Oh? What do you mean, there's not a single thing wrong! [pause=40][emote=Joyous]Hahaha!")
    end)
  
  TASK:JoinCoroutines({coro001, coro002, coro003, coro004})

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Almost forgot...!")
  SOUND:PlayFanfare("Fanfare/Item")
  UI:ResetSpeaker()
  UI:WaitShowDialogue("Arama gives Maru a treasure bag!")
  
  GROUND:CharTurnToCharAnimated(arama, maru, 8)
  GROUND:CharTurnToCharAnimated(azura, maru, 8)
  SV.tarro_town.bag_size = 30
  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Inspired")
  UI:WaitShowDialogue("Woah![pause=50] Cool bag...!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowTimedDialogue("I'm so confused...")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Joyous")
  UI:WaitShowDialogue("Off you two go! Have a wonderful trip!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Wait... we're going?")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowTimedDialogue("Don't worry, I'll...")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowTimedDialogue("...", 20)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("We'll[pause=20] be completely fine, go figure out what that letter was...!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("...uh-huh...?")

  SOUND:PlayBGM("None", true, 120)
  GAME:MoveCameraToChara(0, 0, 0, arama)
  GROUND:TeleportTo(amazuru, 80, 500, Direction.Up, 0)

  
  
  local coro00001 = TASK:BranchCoroutine(function()
    GAME:MoveCamera(0, 500, 240, false)
    end)	
  local coro00002 = TASK:BranchCoroutine(function()
    GROUND:MoveToPosition(arama, arama.Position.X, azura.Position.Y + 100, true, 5)
    GROUND:MoveToPosition(arama, arama.Position.X, azura.Position.Y + 200, false, 3)
    GROUND:MoveToPosition(arama, arama.Position.X, azura.Position.Y + 300, false, 2)
    GROUND:MoveToPosition(arama, arama.Position.X, azura.Position.Y + 400, false, 0.5)
    end)
  
  TASK:JoinCoroutines({coro00001, coro00002})

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Did you let them go?")
  GROUND:CharTurnToCharAnimated(amazuru, arama, 8)

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("They can do it, you know...")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("...")

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("...and they're in good hands.")
  
  GAME:FadeOut(false, 240)
  COMMON.UnlockWithFanfare("deep_tarro_forest", false)
  GAME:CutsceneMode(false)
  GAME:EnterZone("deep_tarro_forest", 0, 0, 0)
end

---TarroForestPassage.Enter(map)
--Engine callback function
function TarroForestPassage.Enter(map)
  
  GAME:FadeIn(20)

end

---TarroForestPassage.Exit(map)
--Engine callback function
function TarroForestPassage.Exit(map)


end

---TarroForestPassage.Update(map)
--Engine callback function
function TarroForestPassage.Update(map)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')

  if GAME:IsKeyDown(66) then
    print("Partner")
  end
  if GAME:IsKeyDown(66) then
    UI:SetSpeaker(azura)
    GROUND:CharTurnToCharAnimated(maru, azura, 4)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("That wasn't so scary, actually.")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Kinda wanna go back home now, though...")
  end
  
end

---TarroForestPassage.GameSave(map)
--Engine callback function
function TarroForestPassage.GameSave(map)


end

---TarroForestPassage.GameLoad(map)
--Engine callback function
function TarroForestPassage.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function TarroForestPassage.Cherry_Action(obj, activator)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local cherry = CH("Cherry")

  GROUND:CharTurnToCharAnimated(cherry, maru, 4)
  UI:SetSpeaker(cherry)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Hey, did you enjoy that dungeon trip?")

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Fun!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Didn't think there would be a Zubat, though...")

  UI:SetSpeaker(cherry)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("A Zubat...? [pause=40]I don't remember that?")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Oh, must be a dungeon thing then?")

  UI:SetSpeaker(cherry)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("...yeah, no,[pause=46] but I'm glad you made it.")
  UI:WaitShowDialogue("The sun here is absolutely divine. [pause=30]G[emote=Happy]et a [speed=0.7]feeeeel.")
end

function TarroForestPassage.TFPassage_DungeonExit_Touch(obj, activator)
  if SV.tarro_town.PieChapter < 4 then
    local azura = CH('Teammate1')
    local maru = CH('PLAYER')
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Maru, apple!")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("O-oh,[pause=15] sorry,[pause=10] I...[pause=25] uh...[emote=Happy][pause=20] forgot,[pause=25] haha...")
  else
    if SV.tarro_town.PieChapter <= 10 then
      GAME:FadeOut(false, 20)
      outside_enter = 4
      GAME:EnterGroundMap("tarro_town_outside", "TarroTownEast_ch2", "TTEast_TarroTownForest")
    else -- == 11
      GAME:FadeOut(false, 20)
      outside_enter = 4
      GAME:EnterGroundMap("tarro_town_outside", "TarroTownEast_ch3", "TTEast_TarroTownForest")
    end
  end
end

function TarroForestPassage.TFPassage_PlazaEnter_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("TarroForestPlaza", "TarroPlaza_Enter")
end

function TarroForestPassage.Buttums_Action(obj, activator)
  local maru = CH("PLAYER")
  local buttums = CH("Buttums")

  GROUND:CharTurnToCharAnimated(buttums, maru, 4)
  UI:SetSpeaker(buttums)
  UI:SetSpeakerEmotion("Normal")
  
  tarro_dungeonpoints = SV.tarro_forest.dungpoints + SV.deep_tarro_forest.dungpoints + SV.tarro_tree_hollows.dungpoints
  if tarro_dungeonpoints >= 300 then
    if GAME:DungeonUnlocked("deep_tarro_forest") == false or GAME:DungeonUnlocked("deep_tarro_forest") == false then
      UI:SetSpeaker(buttums)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("Even though you have all the points...")

      UI:SetSpeaker(buttums)
      UI:SetSpeakerEmotion("Pain")
      UI:WaitShowDialogue("You haven't found all the dungeons.")

      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Come back when you're more experienced. Read the sign.")
    else
    end
  else
    UI:WaitShowDialogue("You are not worthy for this place yet; not enough points. Don't forget to read the sign.")
  end
  
end

function TarroForestPassage.Buttums_1_Action(obj, activator)
  UI:ResetSpeaker()
  if sign_tutorial ~= 1 then
    UI:SetAutoFinish(true)
    UI:WaitShowDialogue("You can get dungeon points by doing certain things in a certain group of dungeons.")
    UI:WaitShowDialogue("Some dungeons, including this one, will only require completion. Other dungeons may require certain items to be turned in, or Pokemon to find.")
    UI:WaitShowDialogue("Getting enough dungeon experience will unlock things that will help you on your future journeys, so be sure to complete as many of these as you can.")
    sign_tutorial = 1
  end

  UI:SetAutoFinish(false)
  print(SV.deep_tarro_forest.dungpoints)
  print(SV.tarro_tree_hollows.dungpoints)
  print(GAME:DungeonUnlocked("tarro_tree_hollows"))
  print(GAME:DungeonUnlocked("deep_tarro_forest"))
  tarro_dungeonpoints = SV.tarro_forest.dungpoints + SV.deep_tarro_forest.dungpoints + SV.tarro_tree_hollows.dungpoints
  if SV.deep_tarro_forest.dungpoints > 0 and SV.tarro_tree_hollows.dungpoints > 0 then
    UI:WaitShowDialogue("You currently have " ..tarro_dungeonpoints.. " dungeon points with the Tarro dungeons.")
    --set up some sort of shop behind Buttums here after Buttums lets the Bluetails know about their feats.
  else
    UI:WaitShowDialogue("You haven't explored all of the dungeons needed for this group.")
    UI:WaitShowDialogue("Recheck the sign after you find all of the Tarro dungeons:")
    if SV.deep_tarro_forest.dungpoints == 0 then
      if GAME:DungeonUnlocked("deep_tarro_forest") == false then
        UI:WaitShowDialogue("An undiscovered dungeon still needs to be explored.")
      else
        UI:WaitShowDialogue("Tarro Deep Forest still needs to be explored.")
      end
    end
    if SV.tarro_tree_hollows.dungpoints == 0 then
      if GAME:DungeonUnlocked("tarro_tree_hollows") == false then
        UI:WaitShowDialogue("An undiscovered dungeon still needs to be explored.")
      else
        UI:WaitShowDialogue("Tarro Tree Hollows still needs to be explored.")
      end
    end
    UI:WaitShowDialogue("You currently have " ..tarro_dungeonpoints.. " dungeon points with the Tarro dungeons.")
  end
end

function TarroForestPassage.BigApple_Action(obj, activator)
  GAME:CutsceneMode(true)
  local azura = CH('Teammate1')
  local maru = CH('PLAYER')
  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Inspired")
  UI:WaitShowDialogue("Gasp!")
  UI:SetSpeakerEmotion("Happy")
  GROUND:MoveToPosition(azura, 269, 299, false, 4)
  GROUND:CharAnimateTurn(azura, Direction.UpLeft, 4, true)
  UI:WaitShowDialogue("Big apple, big apple, big apple![pause=35] P[emote=Joyous]ie, pie, pie, pie!")


  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Alrighty! Now let's bring this back to mom and enjoy some pie.")

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Joyous")
  UI:WaitShowDialogue("Yippee!")

  GAME:CutsceneMode(false)
  GROUND:Hide("BigApple")
  SV.tarro_town.PieChapter = 4
end

function TarroForestPassage.TF_DeepForestEnter_Touch(obj, activator)
  local maru = CH("PLAYER")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(...maybe later...)")
end

function TarroForestPassage.AppleTree_Action(obj, activator)
  UI:ResetSpeaker()
  local choices = {("Yes!"),
    ("No!")}
  UI:BeginChoiceMenu("Shake the tree for an apple?", choices, 1, 2)
  UI:WaitForChoice()
  result = UI:ChoiceResult()
  if result == 1 then
    GROUND:CharSetAnim(CH("PLAYER"), "Attack", false)
    SOUND:PlaySE("Battle/DUN_Tackle")
    GAME:WaitFrames(4)
    SOUND:PlaySE("Battle/DUN_Leaf_Storm_3")

    GAME:WaitFrames(90)

    local apple_give = math.random(100)
    if apple_give >= 55 or SV.tarro_town.apple_tree_get == false then
      SOUND:PlaySE("Battle/EVT_CH02_Item_Place")
      SV.tarro_town.apple_tree_get = true
      
      if apple_give >= 95 then
        UI:WaitShowDialogue("Maru got an apple.[pause=60] It's huge!")
        GAME:GivePlayerItem("food_apple_big")
      else
        UI:WaitShowDialogue("Maru got an apple.")
        GAME:GivePlayerItem("food_apple")
      end
    elseif SV.tarro_town.apple_tree_get == true then
      UI:WaitShowDialogue("Looks like the tree is empty...")
    else
      UI:WaitShowDialogue("Nope.")
    end
  end
  
  
end

return TarroForestPassage



