--[[
    init.lua
    Created: 03/03/2025 23:56:07
    Description: Autogenerated script file for the map GuildFieldMain.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.guildcutscene'

-- Package name
local GuildFieldMain = {}

-------------------------------
-- Map Callbacks
-------------------------------
---GuildFieldMain.Init(map)
--Engine callback function
function GuildFieldMain.Init(map)
  COMMON.RespawnAllies()
  SV.checkpoint = 
  {
    Zone = 'guild_field',
    Segment = -1,
    Map = 1,
    Entry = 0
  }
  if SV.guild.day == 1 then
    if IntroCutscene == true then
      Guild.Day1()
    end
    IntroCutscene = false
  elseif SV.guild.day == 2 then
    if IntroCutscene == true then
      Guild.Day2()
    else
      GROUND:Unhide("Kitkit")
      COMMON.TeleportToMarker(CH("Kitkit"), "mKit_1", Dir8.DownLeft)
    end
    IntroCutscene = false
  end
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
end

---GuildFieldMain.Enter(map)
--Engine callback function
function GuildFieldMain.Enter(map)
  GAME:FadeIn(30)
end

---GuildFieldMain.Exit(map)
--Engine callback function
function GuildFieldMain.Exit(map)


end

---GuildFieldMain.Update(map)
--Engine callback function
function GuildFieldMain.Update(map)
  Partner()
end

---GuildFieldMain.GameSave(map)
--Engine callback function
function GuildFieldMain.GameSave(map)


end

---GuildFieldMain.GameLoad(map)
--Engine callback function
function GuildFieldMain.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function GuildFieldMain.NorthEast_Touch(obj, activator)
  DUNsection = 0
  COMMON.ShowDestinationMenu(SV.guild.dungeons.east, SV.guild.areas.east)
end

function GuildFieldMain.NorthWest_Touch(obj, activator)
  DUNsection = 0
  COMMON.UnlockWithFanfare("apple_forest", false)
  COMMON.ShowDestinationMenu(SV.guild.dungeons.west, SV.guild.areas.west)
end

function GuildFieldMain.StaleApple_Action(obj, activator)
  local leader = CH("PLAYER")
  local second = CH("Teammate1")
  if activator.Nickname == "Maru" then
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(Wonder what these are doing here...)")
  elseif activator.Nickname == "Rexio" then
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(Last time I dealt with apples...?[pause=55] U[emote=Sigh]gh.)")
  else
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Mama could've made pie with these,[pause=15] what a waste!")

    UI:SetSpeaker(second)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Good thing we're getting more.")
  end
end

function GuildFieldMain.TentEntrance_Touch(obj, activator)
  local leader = CH("PLAYER")
  local second = CH("Teammate1")
  local third = CH("Teammate2")

  if activator.Nickname == "Rexio" then
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("I'm gonna go back to bed, you two have fun.")

    UI:SetSpeaker(second)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("That's fine.")
    COMMON.FaceEachother(second, third)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("We'll make some apple pie with the leftover apples ourselves.")

    COMMON.CharRealize("PLAYER")
    UI:SetSpeaker(third)
    UI:SetSpeakerEmotion("Inspired")
    UI:WaitShowDialogue("Gasp![pause=40] Y[emote=Joyous]ippee!")

    COMMON.FaceEachother(leader, third)
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("...I have suddenly changed my mind.")
  elseif activator.Nickname == "Maru" then
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Mm... not yet.")

    UI:SetSpeaker(third)
    UI:SetSpeakerEmotion("Inspired")
    UI:WaitShowDialogue("You... you understand![pause=70] You understand how boring this is gonna be!")

    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Normal")
    COMMON.FaceEachother(leader, third)
    UI:WaitShowDialogue("No, actually, I thought I left something in there.")
  else
    UI:SetSpeaker(leader)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(No,[pause=15] no Azura![pause=45] You must get the apples first!)")
  end
end

function GuildFieldMain.Smear_Action(obj, activator)
  if SV.guild.day == 1 and SV.guild.time == 100 then
    GAME:SetTeamLeaderIndex(0)
    Guild.Day1Done()
    GAME:EnterGroundMap("GuildLvl1", "GuildEnter1")
  else
    local leader = CH("PLAYER")
    local second = CH("Teammate1")
    local zoomer = CH("Zoomer")
    local smear = CH("Smear")

    COMMON.FaceEachother(leader, smear)
    if activator.Nickname == "Rexio" then
      UI:SetSpeaker(leader)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("You wanna explain those missing pillows now?")

      UI:SetSpeaker(smear)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("Well, uhm... it does appear that those deliveries are also late...")

      UI:SetSpeaker(second)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("Then why did you say they were in there.")

      UI:SetSpeaker(smear)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowTimedDialogue("I expected Zoomer to")

      COMMON.FaceEachother(smear, zoomer)

      UI:SetSpeaker(zoomer)
      UI:SetSpeakerEmotion("Angry")
      UI:WaitShowDialogue("Oh no,[pause=45] no no no![pause=30] You are NOT blaming me for this!")
      UI:SetSpeakerEmotion("Stunned")
      UI:WaitShowDialogue("Going out that far is a pain on my wings and you know that!")
    elseif activator.Nickname == "Maru" then
      UI:SetSpeaker(smear)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Do your best out there, Mr. Bluetail.")
    else
      UI:SetSpeaker(smear)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Do your best out there, Ms. Bluetail.")
    end
  end
end

function GuildFieldMain.Zoomer_Action(obj, activator)
  COMMON.FaceEachother(obj, activator)
  if activator.Nickname == "Rexio" then
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Alright, kid. I don't care how good you think you are.")
  else
    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("[speed=0.4]...you two.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("...whatever.")
  end
  UI:WaitShowDialogue("Good adventurers prepare themselves. Use the storage box.")
  UI:WaitShowDialogue("Since you guys are both a team, it should take whatever you guys had when you dungeoned before.")
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("Now leave!")
end

function GuildFieldMain.Storage_Action(obj, activator)
  COMMON:ShowTeamStorageMenu()
end

return GuildFieldMain

