--[[
    init.lua
    Created: 09/15/2025 23:58:43
    Description: Autogenerated script file for the map AppleTownConcert.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local AppleTownConcert = {}

local Coro = function()
  local rai = CH("TheRai")
  local will_move = math.random(100, 200)
  local will_sweat = math.random(25, 75)
  local coro01 = TASK:BranchCoroutine(function()
    COMMON.CharHop("TheRai")
    GAME:WaitFrames(will_move / 2)
    GROUND:CharSetEmote(rai, "angry", 5)
    GAME:WaitFrames(will_move)
    end)	
  local coro02 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(will_sweat)
    GROUND:CharSetEmote(CH("Fleet"), "sweatdrop", 1)
    end)
  TASK:JoinCoroutines({coro01, coro02})
end

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTownConcert.Init(map)
--Engine callback function
function AppleTownConcert.Init(map)
  
end

---AppleTownConcert.Enter(map)
--Engine callback function
function AppleTownConcert.Enter(map)

  GAME:FadeIn(20)

end

---AppleTownConcert.Exit(map)
--Engine callback function
function AppleTownConcert.Exit(map)


end

---AppleTownConcert.Update(map)
--Engine callback function
function AppleTownConcert.Update(map)
  TASK:StartEntityTask(CH("TheRai"), Coro)
  Partner()
end

---AppleTownConcert.GameSave(map)
--Engine callback function
function AppleTownConcert.GameSave(map)


end

---AppleTownConcert.GameLoad(map)
--Engine callback function
function AppleTownConcert.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function AppleTownConcert.TheRai_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Angry")
  UI:WaitShowDialogue("I CANNOT PERFORM![pause=50] My mega stones are not here, therefore the show is postponed!")
end

function AppleTownConcert.Fleet_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("It's not that big big of a deal deal, Rairai.")
end

function AppleTownConcert.AppleTown_Back_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTown", "Enter")
end

return AppleTownConcert

