--[[
    init.lua
    Created: 09/15/2025 23:58:43
    Description: Autogenerated script file for the map AppleTownConcert.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local AppleTownConcert = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTownConcert.Init(map)
--Engine callback function
function AppleTownConcert.Init(map)
  
end

---AppleTownConcert.Enter(map)
--Engine callback function
function AppleTownConcert.Enter(map)

  GAME:FadeIn(20)

end

---AppleTownConcert.Exit(map)
--Engine callback function
function AppleTownConcert.Exit(map)


end

---AppleTownConcert.Update(map)
--Engine callback function
function AppleTownConcert.Update(map)


end

---AppleTownConcert.GameSave(map)
--Engine callback function
function AppleTownConcert.GameSave(map)


end

---AppleTownConcert.GameLoad(map)
--Engine callback function
function AppleTownConcert.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function AppleTownConcert.AppleTown_Back_Touch(obj, activator)
  GAME:EnterGroundMap("AppleTown", "Enter")
end

return AppleTownConcert

