--[[
    init.lua
    Created: 08/11/2024 15:18:02
    Description: Autogenerated script file for the map TarroTownOutside.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local TarroTownOutside = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownOutside.Init(map)
--Engine callback function
function TarroTownOutside.Init(map)
  GAME:SetCanSwitch(false)
  if GAME:GetPlayerPartyCount() == 1 then
    local mon_id = RogueEssence.Dungeon.MonsterID("azurill", 0, "normal", Gender.Female)

    local p = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 4, "", 0)
    p.IsFounder = false
    p.IsPartner = true
    p.Nickname = "Azura"

    _DATA.Save.ActiveTeam.Players:Add(p)
  else 
    if GAME:GetPlayerPartyCount() >= 2 then
      GAME:RemovePlayerAssembly(3)
    end
  end
  GAME:GetPlayerPartyMember(0).IsPartner = true 
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  if outside_enter == 1 then
    GROUND:TeleportTo(partner, 27, 379, Direction.Right, 0)
    GAME:FadeIn(20)
  else
    GAME:FadeIn(20)
  end
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true
  

  TarroTownOutside.CloudWatch()
  GAME:CutsceneMode(false)
end

---TarroTownOutside.Enter(map)
--Engine callback function
function TarroTownOutside.Enter(map)
    
  
end

function TarroTownOutside.CloudWatch()
  if SV.tarro_town.PieChapter >= 0 then
    TarroTownOutside.Enter(map)
  else
    local maru = CH("PLAYER")
    local azura = CH("Teammate1")
    GAME:CutsceneMode(true)

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("It's...[pause=40] relaxing.[pause=0] Sitting here, watching the cloud go by...")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Ooh! That one looks like me! Look!")
    SV.tarro_town.PieChapter = 0
    local talk_evt = RogueEssence.Dungeon.BattleScriptEvent("AllyInteract")
    _DATA.Save.ActiveTeam.Players[1].ActionEvents:Add(talk_evt)
    TarroTownOutside.Enter(map)
  end
end

---TarroTownOutside.Exit(map)
--Engine callback function
function TarroTownOutside.Exit(map)


end

---TarroTownOutside.Update(map)
--Engine callback function
function TarroTownOutside.Update(map)  
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local puchi = CH('Puchi')

  if GAME:IsKeyDown(66) then
    print("Partner")
  end
  if GAME:IsKeyDown(66) then
    if SV.tarro_town.PieChapter < 2 then
      UI:SetSpeaker(azura)
      GROUND:CharTurnToCharAnimated(maru, azura, 4)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Let's go home and get some pie!")

      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Gee, not like it's going anywhere.")

      UI:SetSpeaker(azura)
      UI:SetSpeakerEmotion("Sad")
      UI:WaitShowDialogue("But what if it gets c[speed=0.7]oooo[speed=1.0]ld?!")
      
      GROUND:CharTurnToCharAnimated(puchi, maru, 4)
      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Don't think it would get cold that fast...")
      
      GROUND:CharTurnToCharAnimated(maru, puchi, 4)
      GROUND:CharTurnToCharAnimated(azura, puchi, 4)
      UI:SetSpeaker(puchi)
      UI:SetSpeakerEmotion("Inspired")
      UI:WaitShowDialogue("You guys are getting pie?!")

      UI:SetSpeaker(azura)
      UI:SetSpeakerEmotion("Angry")
      UI:WaitShowDialogue("Not enough for you!")
    elseif SV.tarro_town.PieChapter >= 2 and SV.tarro_town.PieChapter < 4 then
      if SV.tarro_town.PieChapter == 2.1 then
        UI:SetSpeaker(azura)
        GROUND:CharTurnToCharAnimated(maru, azura, 4)
        UI:SetSpeakerEmotion("Angry")
        UI:WaitShowDialogue("That fail made me mad...!")
      elseif SV.tarro_town.PieChapter == 2.2 then
        UI:SetSpeaker(azura)
        GROUND:CharTurnToCharAnimated(maru, azura, 4)
        UI:SetSpeakerEmotion("Angry")
        UI:WaitShowDialogue("Ugh, dumb bat!")
      end
      UI:SetSpeaker(azura)
      GROUND:CharTurnToCharAnimated(maru, azura, 4)
      UI:SetSpeakerEmotion("Determined")
      UI:WaitShowDialogue("What are we doing here?!")
      UI:WaitShowDialogue("We need the apple before it gets late!")
    elseif SV.tarro_town.PieChapter == 4 then
      UI:SetSpeaker(azura)
      GROUND:CharTurnToCharAnimated(maru, azura, 4)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("I'd love to watch cloud more, but can we get pie first?")
      UI:WaitShowDialogue("The Big Apple might spoil!")
    else
      UI:SetSpeaker(azura)
      GROUND:CharTurnToCharAnimated(maru, azura, 4)
      UI:SetSpeakerEmotion("Inspired")
      UI:WaitShowDialogue("Pretty clouds...!")

      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Cloud watching would be fun, wouldn't it?")
    end
  end
end

---TarroTownOutside.GameSave(map)
--Engine callback function
function TarroTownOutside.GameSave(map)


end

---TarroTownOutside.GameLoad(map)
--Engine callback function
function TarroTownOutside.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function TarroTownOutside.TTOutside_WExit_Touch(obj, activator)
  outside_enter = 0
  GAME:FadeOut(false, 20)
  if SV.tarro_town.PieChapter < 5 then
    GAME:EnterGroundMap("TarroTownEast", "TTEast_WEnter")
  else
    GAME:EnterGroundMap("TarroTownEast_ch2", "TTEast_WEnter")
  end
  
end

function TarroTownOutside.TTOutsideSign_Action(obj, activator)
  UI:ResetSpeaker()
  UI:SetAutoFinish(true)
  UI:WaitShowDialogue("<- Tarro Town East \n Tarro Town West ->")
  UI:SetAutoFinish(false)
end

function TarroTownOutside.TTOutside_EExit_Touch(obj, activator)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local puchi = CH('Puchi')
  GROUND:CharTurnToCharAnimated(puchi, maru, 4)
  UI:SetSpeaker(puchi)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Oi.")

  GROUND:CharTurnToCharAnimated(maru, puchi, 4)
  GROUND:CharTurnToCharAnimated(azura, puchi, 4)
  UI:SetSpeaker(puchi)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("For the sake of your ears, please don't go that way.")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ma's all mad again.")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Oh. [pause=25]Darn.")
end

function TarroTownOutside.Puchi_Action(obj, activator)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local puchi = CH('Puchi')
  
  if SV.tarro_town.PieChapter == 0 then  
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GROUND:CharTurnToCharAnimated(azura, puchi, 4)
    GROUND:CharTurnToCharAnimated(puchi, maru, 4)
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchiiii!")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Yo.")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("What are you doing out here?")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Not much...")
    UI:WaitShowDialogue("...mostly waiting on my mom to calm down again.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Again...?")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Yeah... it's not my day.[pause=35] Broke[emote=Worried] my favorite toy, too...")
    UI:SetSpeakerEmotion("Happy")
    GROUND:CharAnimateTurn(puchi, Direction.Up, 4, false)
    UI:WaitShowDialogue("The clouds are calming me down though, so puffy today.")
  elseif SV.tarro_town.PieChapter == 1 then 
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GROUND:CharTurnToCharAnimated(azura, puchi, 4)
    GROUND:CharTurnToCharAnimated(puchi, maru, 4)
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchi!")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("W-wha... you ate all your pie already?!")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("At least ask for seconds, haha!")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("No, actually,[pause=43] we did not.")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Special3")
    UI:WaitShowDialogue("...[pause=61]then why are you here?")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Yeah, why are we here?")

    GROUND:CharTurnToCharAnimated(maru, azura, 4)
    GAME:WaitFrames(45)
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GAME:WaitFrames(45)
    GROUND:CharTurnToCharAnimated(maru, azura, 4)
    GAME:WaitFrames(25)
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GAME:WaitFrames(100)

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Special0")
    UI:WaitShowDialogue("I dunno.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Maru!")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Fine, fine, we're going now.")
  elseif SV.tarro_town.PieChapter >= 2 then
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GROUND:CharTurnToCharAnimated(azura, puchi, 4)
    GROUND:CharTurnToCharAnimated(puchi, maru, 4)
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchi!")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Hello, Azura.[pause=35] Hello, Maru.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("[speed=0.4]...s[speed=1.0]trange,[pause=0] I'd expect a bunch of crumbs on your face by now...")

    UI:SetSpeaker(azura)
    GROUND:CharTurnToCharAnimated(maru, azura, 4)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("[speed=0.2]...")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("Yeah...[pause=41] mom ran [emote=Worried]out of big apples.")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oh,[pause=25] so you have to get more,[pause=25] I'm assuming.")
    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    UI:WaitShowDialogue("I'd say to be careful, but...[pause=0] I[emote=Happy]'d say you'll both be fine.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("[speed=0.1]...![speed=1.0][pause=30] W[emote=Surprised]ait![pause=40] T[emote=Inspired]hat must mean that you have a Big Apple!")
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("Gimme, gimme, gimme!")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("[speed=0.2]Mmmmmmmmm,[speed=1.0][pause=25] about that...")
    UI:WaitShowDialogue("[pause=45]...I ate it.")

    GAME:WaitFrames(50)
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("...")

    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("It was delicious.")
  end
  
end

return TarroTownOutside

