--[[
    init.lua
    Created: 08/11/2024 15:18:02
    Description: Autogenerated script file for the map TarroTownOutside.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.TarroTownOutside.cutscene'

-- Package name
local TarroTownOutside = {}

local Coro = function()
  GROUND:CharSetEmote(CH("Brasion"), "minigame", 1)
  GAME:WaitFrames(96)
end

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownOutside.Init(map)
--Engine callback function
function TarroTownOutside.Init(map)
  GAME:SetCanSwitch(false)
  
  if SV.tarro_town.PieChapter >= 5 then
    GROUND:Hide("Puchi")
  end
  if GAME:GetPlayerPartyCount() == 1 then
    local mon_id = RogueEssence.Dungeon.MonsterID("azurill", 0, "normal", Gender.Female)

    local p = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 4, "", 0)
    p.IsFounder = false
    p.IsPartner = true
    p.Nickname = "Azura"

    _DATA.Save.ActiveTeam.Players:Add(p)
  else 
    if GAME:GetPlayerPartyCount() >= 2 then
      GAME:RemovePlayerAssembly(3)
    end
  end
  GAME:GetPlayerPartyMember(0).IsPartner = true 
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  Outside.CloudWatch()
  if OutEnter == 1 then
    GROUND:TeleportTo(partner, 478, 379, Direction.Left, 0)
  elseif OutEnter == 2 then
    GROUND:TeleportTo(partner, 53, 379, Direction.Right, 0)
  end
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true

  if (wager_up ~= 0 and cup_total_points ~= 0) and (wager_up ~= nil and cup_total_points ~= nil) then
    TarroTownOutside.Reward()
  end  
  GAME:CutsceneMode(false)
end

---TarroTownOutside.Enter(map)
--Engine callback function
function TarroTownOutside.Enter(map)
    
  GAME:FadeIn(20)

end


---TarroTownOutside.Exit(map)
--Engine callback function
function TarroTownOutside.Exit(map)


end

---TarroTownOutside.Update(map)
--Engine callback function
function TarroTownOutside.Update(map)  
  Partner()
  TASK:StartEntityTask(CH("Brasion"), Coro)
end

---TarroTownOutside.GameSave(map)
--Engine callback function
function TarroTownOutside.GameSave(map)


end

---TarroTownOutside.GameLoad(map)
--Engine callback function
function TarroTownOutside.GameLoad(map)

  GAME:FadeIn(20)

end

function TarroTownOutside.Reward(map)
  local brasi = CH("Brasion")

  UI:SetSpeaker(brasi)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Let's see...")

  UI:SetSpeaker(brasi)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("You wagered " .. wager_up .. " Poke")

  UI:SetSpeaker(brasi)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("You got " .. cup_total_points .. " points.")

  UI:SetSpeaker(brasi)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("So that means...")

  local winnings = wager_up * cup_total_points
  if winnings < 0 then
    if GAME:GetPlayerMoney() < math.abs(winnings) then
      GAME:RemoveFromPlayerMoney(GAME:GetPlayerMoney())
    else
      GAME:RemoveFromPlayerMoney(math.abs(winnings))
    end
    SOUND:PlaySE("Battle/DUN_Money")
    UI:ResetSpeaker()
    UI:WaitShowDialogue("Brasion takes "..winnings.." Poke from Maru.")
  else
    GAME:AddToPlayerMoney(winnings)
    SOUND:PlaySE("Battle/DUN_Money")
    UI:ResetSpeaker()
    UI:WaitShowDialogue("Brasion gives Maru "..winnings.." Poke.")
  end
  wager_up = 0
  cup_total_points = 0
end
-------------------------------
-- Entities Callbacks
-------------------------------

--- Entrances
function TarroTownOutside.TTOutside_WExit_Touch(obj, activator)
  OutEnter = 0
  GAME:FadeOut(false, 20)
  if SV.tarro_town.PieChapter < 5 then    
    if SV.GroundTutorial == 0 then
      SOUND:PlayFanfare("Fanfare/Note")
      UI:ResetSpeaker()
			UI:WaitShowDialogue("Sometimes, you may get lost on your adventure.[pause=10] Or maybe you just need to talk to someone.")
      UI:WaitShowDialogue("If you press [B] on your keyboard,[pause=10] you can talk to whoever is in your second slot.")
      UI:WaitShowDialogue("There's currently no button for this on a controller,[pause=10] please be patient as the game continues to be patched.")
      SV.GroundTutorial = SV.GroundTutorial + 1
    end
    GAME:EnterGroundMap("TarroTownEast", "TTEast_WEnter")
  elseif SV.tarro_town.PieChapter < 10 then
    GAME:EnterGroundMap("TarroTownEast_ch2", "TTEast_WEnter")
  else
    GAME:EnterGroundMap("TarroTownEast_ch3", "TTEast_WEnter")
  end
end

function TarroTownOutside.TTOutsideSign_Action(obj, activator)
  UI:ResetSpeaker()
  UI:SetAutoFinish(true)
  UI:WaitShowDialogue("Tarro Town East ->\n <- Tarro Town West")
  UI:SetAutoFinish(false)
end

function TarroTownOutside.TTOutside_EExit_Touch(obj, activator)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local puchi = CH('Puchi')
  if SV.tarro_town.PieChapter < 5 then  
    GROUND:CharTurnToCharAnimated(puchi, maru, 4)
    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oi.")

    GROUND:CharTurnToCharAnimated(maru, puchi, 4)
    GROUND:CharTurnToCharAnimated(azura, puchi, 4)
    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("For the sake of your ears, please don't go that way.")
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Ma's all mad again.")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oh. [pause=25]Darn.")
  elseif SV.tarro_town.PieChapter <= 10 then
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Probably not the time...")
  else
    GAME:FadeOut(false, 20)
    GAME:EnterGroundMap("TarroTownWest", "TarroTownWest_Enter")
  end
end

--- Characters
function TarroTownOutside.Puchi_Action(obj, activator)
  local azura = CH('Teammate1')
  if SV.tarro_town.PieChapter == 0 then  
    COMMON.FaceEachother(obj, activator)
    GROUND:CharTurnToCharAnimated(azura, obj, 4)
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchiiii!")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Yo.")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("What are you doing out here?")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Not much...")
    UI:WaitShowDialogue("...mostly waiting on my mom to calm down again.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Again...?")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Yeah... it's not my day.[pause=35] Broke[emote=Worried] my favorite toy, too...")
    UI:SetSpeakerEmotion("Happy")
    GROUND:CharAnimateTurn(obj, Direction.Up, 4, false)
    UI:WaitShowDialogue("The clouds are calming me down though, so puffy today.")
  elseif SV.tarro_town.PieChapter == 1 then
    COMMON.FaceEachother(obj, activator)
    GROUND:CharTurnToCharAnimated(azura, obj, 4)
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchi!")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("W-wha... you ate all your pie already?!")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("At least ask for seconds, haha!")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("No, actually,[pause=43] we did not.")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Special3")
    UI:WaitShowDialogue("...[pause=61]then why are you here?")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Yeah, why are we here?")

    GROUND:CharTurnToCharAnimated(activator, azura, 4)
    GAME:WaitFrames(45)
    GROUND:CharTurnToCharAnimated(activator, obj, 4)
    GAME:WaitFrames(45)
    GROUND:CharTurnToCharAnimated(activator, azura, 4)
    GAME:WaitFrames(25)
    GROUND:CharTurnToCharAnimated(activator, obj, 4)
    GAME:WaitFrames(100)

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Special0")
    UI:WaitShowDialogue("I dunno.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Maru!")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Fine, fine, we're going now.")
  elseif SV.tarro_town.PieChapter < 3 then
    GROUND:CharTurnToCharAnimated(activator, obj, 4)
    GROUND:CharTurnToCharAnimated(azura, obj, 4)
    GROUND:CharTurnToCharAnimated(obj, activator, 4)
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchi!")

    UI:SetSpeaker(obj)
    UI:WaitShowDialogue("Hello, Azura.[pause=35] Hello, Maru.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("[speed=0.2]...s[speed=1.0]trange,[pause=0] I'd expect a bunch of crumbs on your face by now...")

    UI:SetSpeaker(azura)
    GROUND:CharTurnToCharAnimated(activator, azura, 4)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("[speed=0.2]...")

    UI:SetSpeaker(activator)
    UI:WaitShowDialogue("Yeah...[pause=41] mom ran [emote=Worried]out of big apples.")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oh,[pause=25] so you have to get more,[pause=25] I'm assuming.")
    GROUND:CharTurnToCharAnimated(activator, obj, 4)
    UI:WaitShowDialogue("I'd say to be careful, but...[pause=0] I[emote=Happy]'d say you'll both be fine.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Normal")

    local function azura_gasp()
      COMMON.CharExclaim("Teammate1")
    end

    COMMON.CharQuestion("Teammate1")
    UI:WaitShowDialogue("[speed=0.1]...![speed=1.0][pause=30] W[emote=Surprised]a[script=0]it![pause=40] T[emote=Inspired]hat must mean that you have a Big Apple!", {azura_gasp})
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("Gimme, gimme, gimme!")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("[speed=0.2]Mmmmmmmmm,[speed=1.0][pause=25] about that...")
    UI:WaitShowDialogue("[pause=45]...I ate it.")

    GAME:WaitFrames(50)
    COMMON.CharAngry("Teammate1")
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("...")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("It was delicious.")
  elseif SV.tarro_town.PieChapter <= 5 then
    GROUND:CharTurnToCharAnimated(activator, obj, 4)
    GROUND:CharTurnToCharAnimated(azura, obj, 4)
    GROUND:CharTurnToCharAnimated(obj, activator, 4)
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Puchi!")

    UI:SetSpeaker(obj)
    GROUND:CharTurnToCharAnimated(obj, activator, 4)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("[speed=0.2]...")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("If my nose isn't acting up, I smell Big Apple.")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("You guys did it, congrats!")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("Pie[pause=20] pie[pause=20] pie[pause=20] pie!")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowTimedDialogue("Share???", 20)

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("No.")

    UI:SetSpeaker(obj)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Heck.")
  end
end

function TarroTownOutside.Oink_Action(obj, activator)
  COMMON.FaceEachother(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I just wanted to hang out,[pause=30] didn't know about all the moving and stuff.")
end

function TarroTownOutside.Reeshi_Action(obj, activator)
  COMMON.FaceEachother(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("A lot of baaaaad Pokemon from the dungeons are turning good for better homes and stuff.")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("But thaaaaaat also means we need more than a few houses as places to live.")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("The noise from the building is super loud, baa...")
end

function TarroTownOutside.Roll_Action(obj, activator)
  COMMON.FaceEachother(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Comin' outtaf th' Jugnion Distric' 'cuza all the monsters movin' in.[pause=0] It'sso calm here, an' me pa'n I can fin'lly get some walkin' in.")
end

--- Other
function TarroTownOutside.CupShuffle_Action(obj, activator)
  local brasi = CH("Brasion")
  if GAME:GetPlayerMoney() < 25 then
    UI:SetSpeaker(brasi)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Sorry, but you need money to play.[pause=15] Come back later.")
  else
    UI:SetSpeaker(brasi)
    UI:SetSpeakerEmotion("Happy")
    local choices = {
      ("Let's play!"),
      ("No thanks.")
    }
    UI:BeginChoiceMenu("Hey, wanna play some cup shuffle?", choices, 1, 2)
    UI:WaitForChoice()
    result = UI:ChoiceResult()
    if result == 1 then
      GAME:EnterGroundMap("CupShuffle", "Mark")
    else
      UI:SetSpeaker(brasi)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Mkay.")
    end
  end
end

function TarroTownOutside.CloudWatch_Touch(obj, activator)
  local azura = CH('Teammate1')
  if SV.tarro_town.PieChapter <= 5 then
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Uhhhhh... hello?!?![pause=0] Piiiiiiieee????")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oh yeah.")
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("The clouds are still up there.[pause=30] ...maybe we'll watch them later.")
  end
end

return TarroTownOutside

