--[[
    init.lua
    Created: 04/29/2026 16:07:51
    Description: Autogenerated script file for the map DarkGuild.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.DarkGuild.cutscene'

-- Package name
local DarkGuild = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DarkGuild.Init(map)
--Engine callback function
function DarkGuild.Init(map)
  if SV.Story.sect == 2 then
    Darker.Spotlight()
  else
    EXPLCOMMON.AllyFollow(true, false)
  end
end

---DarkGuild.Enter(map)
--Engine callback function
function DarkGuild.Enter(map)

  GAME:FadeIn(20)

end

---DarkGuild.Exit(map)
--Engine callback function
function DarkGuild.Exit(map)


end

---DarkGuild.Update(map)
--Engine callback function
function DarkGuild.Update(map)


end

---DarkGuild.GameSave(map)
--Engine callback function
function DarkGuild.GameSave(map)


end

---DarkGuild.GameLoad(map)
--Engine callback function
function DarkGuild.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return DarkGuild

