--[[
    init.lua
    Created: 01/24/2025 19:29:56
    Description: Autogenerated script file for the map MaruHomeFood.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.MaruHomeFood.cooking'

-- Package name
local MaruHomeFood = {}

-------------------------------
-- Map Callbacks
-------------------------------
---MaruHomeFood.Init(map)
--Engine callback function
function MaruHomeFood.Init(map)
  SV.tarro_town.cooking_tutorial_done = 1
  MaruHomeFood.CookingGameplay()
end

function MaruHomeFood.CookingGameplay(map)
  Cooking(0, 0, 0)
end

---MaruHomeFood.Enter(map)
--Engine callback function
function MaruHomeFood.Enter(map)

  GAME:FadeIn(20)
  
end

---MaruHomeFood.Exit(map)
--Engine callback function
function MaruHomeFood.Exit(map)


end

---MaruHomeFood.Update(map)
--Engine callback function
function MaruHomeFood.Update(map)


end

---MaruHomeFood.GameSave(map)
--Engine callback function
function MaruHomeFood.GameSave(map)


end

---MaruHomeFood.GameLoad(map)
--Engine callback function
function MaruHomeFood.GameLoad(map)

  GAME:FadeIn(20)

end



-------------------------------
-- Entities Callbacks
-------------------------------


return MaruHomeFood

