--[[
    init.lua
    Created: 06/09/2025 22:54:33
    Description: Autogenerated script file for the map EntohTownSouth.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'explorers_of_friending.ground.EntohTownSouth.cutscene'

-- Package name
local EntohTownSouth = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownSouth.Init(map)
--Engine callback function
function EntohTownSouth.Init(map)
  South.BossBegin()
end

---EntohTownSouth.Enter(map)
--Engine callback function
function EntohTownSouth.Enter(map)
  if not Todungeonscene then
    GAME:FadeIn(20)
  else
  end
end

---EntohTownSouth.Exit(map)
--Engine callback function
function EntohTownSouth.Exit(map)


end

---EntohTownSouth.Update(map)
--Engine callback function
function EntohTownSouth.Update(map)


end

---EntohTownSouth.GameSave(map)
--Engine callback function
function EntohTownSouth.GameSave(map)


end

---EntohTownSouth.GameLoad(map)
--Engine callback function
function EntohTownSouth.GameLoad(map)

  GAME:FadeIn(20)

end

return EntohTownSouth

