--[[
    init.lua
    Created: 11/20/2025 10:26:58
    Description: Autogenerated script file for the map DesertSE.
]]--
-- Commonly included lua functions and data
require 'origin.common'
local balwalk1, balwalk2, balwalk3, balwalk4 = 0, 0, 0, 0

local function treasure_hunters()
  local coro01 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(balwalk1)
    GROUND:CharSetEmote(CH("Bal1"), "sweating", 1)
    balwalk1 = math.random(100, 250)
    end)
  local coro02 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(balwalk2)
    GROUND:CharSetEmote(CH("Bal2"), "question", 1)
    balwalk2 = math.random(100, 250)
    end)
  local coro03 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(balwalk3)
    GROUND:CharSetEmote(CH("Bal3"), "angry", 1)
    balwalk3 = math.random(100, 250)
    end)
  local coro04 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(balwalk4)
    GROUND:CharSetEmote(CH("Bal4"), "sweating", 1)
    balwalk4 = math.random(100, 250)
    end)
  TASK:JoinCoroutines({coro01, coro02, coro03, coro04})
end
-- Package name
local DesertSE = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DesertSE.Init(map)
--Engine callback function
function DesertSE.Init(map)
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  GROUND:TeleportTo(CH("Teammate1"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  GROUND:TeleportTo(CH("Teammate2"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.UpRight, 0)
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)

  COMMON.CreateWalkArea("Bal1", CH("Bal1").Position.X, CH("Bal1").Position.Y, 200, 200)
  COMMON.CreateWalkArea("Bal2", CH("Bal2").Position.X, CH("Bal2").Position.Y, 200, 200)
  COMMON.CreateWalkArea("Bal3", CH("Bal3").Position.X, CH("Bal3").Position.Y, 200, 200)
  COMMON.CreateWalkArea("Bal4", CH("Bal4").Position.X, CH("Bal4").Position.Y, 200, 200)
end

---DesertSE.Enter(map)
--Engine callback function
function DesertSE.Enter(map)

  GAME:FadeIn(20)

end

---DesertSE.Exit(map)
--Engine callback function
function DesertSE.Exit(map)


end

---DesertSE.Update(map)
--Engine callback function
function DesertSE.Update(map)
  TASK:StartEntityTask(CH("Gunke"), treasure_hunters)
  Partner()
end

---DesertSE.GameSave(map)
--Engine callback function
function DesertSE.GameSave(map)


end

---DesertSE.GameLoad(map)
--Engine callback function
function DesertSE.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function DesertSE.Gunke_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Those four haven't moved out of the desert all day, keh.")
end

-- Exits

function DesertSE.N_Touch(obj, activator)
  GAME:EnterGroundMap("DesertNE", "SouthEnter")
end

function DesertSE.NW_Touch(obj, activator)
  GAME:EnterGroundMap("DesertN", "SouthEastEnter")
end

function DesertSE.W_Touch(obj, activator)
  GAME:EnterGroundMap("DesertS", "EastEnter")
end

return DesertSE

