--[[
    init.lua
    Created: 04/11/2025 09:13:22
    Description: Autogenerated script file for the map EntohTownNorth.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.EntohTownNorth.cutscene'

-- Package name
local EntohTownNorth = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownNorth.Init(map)
--Engine callback function
function EntohTownNorth.Init(map)
  Todungeonscene = false
  if SV.entoh_town.HelperChapter == 0 then
    Entoh.PanchChallenge()
  elseif SV.entoh_town.thicket.result > -1 then
    if SV.entoh_town.HelperChapter == 1 then
      Entoh.Resulting()
    end
  end
end

---EntohTownNorth.Enter(map)
--Engine callback function
function EntohTownNorth.Enter(map)

  if not Todungeonscene then
    GAME:FadeIn(20)
  else
    Todungeonscene = false
  end
end

---EntohTownNorth.Exit(map)
--Engine callback function
function EntohTownNorth.Exit(map)


end

---EntohTownNorth.Update(map)
--Engine callback function
function EntohTownNorth.Update(map)


end

---EntohTownNorth.GameSave(map)
--Engine callback function
function EntohTownNorth.GameSave(map)


end

---EntohTownNorth.GameLoad(map)
--Engine callback function
function EntohTownNorth.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function EntohTownNorth.Entoh_SouthNExit_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownCenter", "EnterMark_North")
end

function EntohTownNorth.Enoth_DeliveryNEnter_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownDelivery", "EnterMark_DSouth")
end

function EntohTownNorth.Panch_Action(obj, activator)
  local panch = CH("Panch")
  local rexio = CH("PLAYER")
  COMMON.FaceEachother(obj, activator)
  if SV.entoh_town.HelperChapter < 3 then
    if SV.entoh_town.thicket.result == -1 then
      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Angry")
      UI:WaitShowDialogue("W-... whateeeeeeever!")
    elseif SV.entoh_town.thicket.result > 4 then
      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("I am impressed!")
    else
      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Even if you sucked, you still did it! Hooray!")
    end
  elseif SV.entoh_town.AdventureChapter > 0 then
    if SV.entoh_town.thicket.result == -1 then
      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Heh, so maybe you are brave enough to go places.")

      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Who told you I was leaving?")

      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Dewey did.")
    else
      UI:SetSpeaker(panch)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Yo, Rexiooooo!")
    end
  else
    UI:SetSpeaker(panch)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Wow, more chores?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Nah, gotta find a key.")

    COMMON.CharSweatdrop("Panch")
    UI:SetSpeaker(panch)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Booooooring!")
  end
end

return EntohTownNorth

