--[[
    init.lua
    Created: 01/31/2025 20:20:43
    Description: Autogenerated script file for the map DeepForestBreak.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local DeepForestBreak = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DeepForestBreak.Init(map)
--Engine callback function
function DeepForestBreak.Init(map)

  DeepForestBreak.ZoomUp()
end

function DeepForestBreak.ZoomUp(map)

  GAME:FadeIn(20)

end

---DeepForestBreak.Enter(map)
--Engine callback function
function DeepForestBreak.Enter(map)

  GAME:FadeIn(20)

end

---DeepForestBreak.Exit(map)
--Engine callback function
function DeepForestBreak.Exit(map)


end

---DeepForestBreak.Update(map)
--Engine callback function
function DeepForestBreak.Update(map)


end

---DeepForestBreak.GameSave(map)
--Engine callback function
function DeepForestBreak.GameSave(map)


end

---DeepForestBreak.GameLoad(map)
--Engine callback function
function DeepForestBreak.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return DeepForestBreak

