--[[
    init.lua
    Created: 06/29/2025 10:33:41
    Description: Autogenerated script file for the map ApartmentRooms_ch2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local ApartmentRooms_ch2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---ApartmentRooms_ch2.Init(map)
--Engine callback function
function ApartmentRooms_ch2.Init(map)

end

---ApartmentRooms_ch2.Enter(map)
--Engine callback function
function ApartmentRooms_ch2.Enter(map)

  GAME:FadeIn(20)

end

---ApartmentRooms_ch2.Exit(map)
--Engine callback function
function ApartmentRooms_ch2.Exit(map)


end

---ApartmentRooms_ch2.Update(map)
--Engine callback function
function ApartmentRooms_ch2.Update(map)


end

---ApartmentRooms_ch2.GameSave(map)
--Engine callback function
function ApartmentRooms_ch2.GameSave(map)


end

---ApartmentRooms_ch2.GameLoad(map)
--Engine callback function
function ApartmentRooms_ch2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- CharFunc
sand_talk = 0
rex_talk = 0
function ApartmentRooms_ch2.Mouse_Action(obj, activator)
  local mouse = CH("Mouse")
  COMMON.FaceEachother(activator, mouse)
  if sand_talk == 0 then
    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Hey, Rexio.[pause=10] Hope you're well.[pause=10]")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Me?[pause=10] Maybe Tidy hates me.[pause=10] I'm not all clean.[pause=10]")
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("I'm not too clean.[pause=10] I'm just more organized.[pause=10] Even more than Tidy.[pause=10]")
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("I hope we're friends.[pause=10] She never shows it.[pause=10] Like, ever.[pause=10]")
    sand_talk = 1
  else
    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Guess it doesn't matter.[pause=10] I have other friends...[pause=10]")
  end
  
end

-- EnterFunc

function ApartmentRooms_ch2.ApartExit_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownCenter_ch2", "HomeMarker")
end

function ApartmentRooms_ch2.RexioHome_Enter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  if SV.entoh_town.HelperChapter < 9 then
    GAME:EnterGroundMap("RexioHome_ch2", "RexioHomeWay")
  else
    GAME:EnterGroundMap("RexioHome", "RexioHomeWay")
  end
end

function ApartmentRooms_ch2.EmptyEnter_Touch(obj, activator)
  local rexio = CH("PLAYER")

  if SV.entoh_town.HelperChapter == 9 then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("...")
  else
    if rex_talk == 0 then
      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("(Oh wooooooooow. Very interesting stuff in there.)")
      rex_talk = 1
    else
      GROUND:CharAnimateTurnTo(rexio, Dir8.Down, 3)
      COMMON.CharAngry("PLAYER")
      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("(If my sarcasm still somehow isn't obvious...!)")
    end
  end
end

function ApartmentRooms_ch2.EmptyEnter_0_Touch(obj, activator)
  local rexio = CH("PLAYER")

  if rex_talk == 0 then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(Oh wooooooooow. Very interesting stuff in there.)")
    rex_talk = 1
  else
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(If my sarcasm wasn't obvious...)")
  end
end

return ApartmentRooms_ch2

