--[[
    init.lua
    Created: 09/11/2024 10:08:21
    Description: Autogenerated script file for the map deep_tarro_forest.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local deep_tarro_forest = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---deep_tarro_forest.Init(zone)
--Engine callback function
function deep_tarro_forest.Init(zone)


end

---deep_tarro_forest.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function deep_tarro_forest.EnterSegment(zone, rescuing, segmentID, mapID)
    if DUN_failure then
        
    end
end

---deep_tarro_forest.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function deep_tarro_forest.ExitSegment(zone, result, rescue, segmentID, mapID)
    print("Hello!")
    if SV.deep_tarro_forest.revisit == false then
        if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
            DUN_failure = true
            if segmentID == 0 then
                COMMON.EndDungeonDay(result, "deep_tarro_forest", -1, 0, 0)
            elseif segmentID == 1 then
                COMMON.EndDungeonDay(result, "deep_tarro_forest", -1, 1, 0)
            end
        else
            if SV.tarro_forest.ZoomerDefeated == false then
                if segmentID == 0 then
                    GAME:EnterZone("deep_tarro_forest", -1, 1, 0)
                else
                    SV.tarro_forest.ZoomerDefeated = true
                    SV.tarro_forest.dungpoints = SV.tarro_forest.dungpoints + 50
                    COMMON.EndDungeonDay(result, "deep_tarro_forest", -1, 0, 0)
                end
            else
                if segmentID == 0 then
                    SV.tarro_forest.dungpoints = SV.tarro_forest.dungpoints + 50
                    SV.tarro_town.apple_tree_get = false
                    COMMON.EndDungeonDay(result, "deep_tarro_forest", -1, 0, 0)
                end
            end
        end
    else
        if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
            if segmentID == 0 then
            SV.tarro_town.PieChapter = 2.1
            elseif segmentID == 1 then
            SV.tarro_town.PieChapter = 2.2
            end
            COMMON.EndDungeonDay(result, "tarro_town_outside", -1, 1, 2)
        else
            if SV.tarro_forest.ZoomerDefeated == false then
                if segmentID == 0 then
                    GAME:EnterZone("tarro_forest", -1, 0, 0)
                else
                    SV.tarro_forest.ZoomerDefeated = true
                    SV.tarro_forest.dungpoints = SV.tarro_forest.dungpoints + 50
                    COMMON.EndDungeonDay(result, "tarro_forest", -1, 0, 0)
                end
            else
                if segmentID == 0 then
                    COMMON.EndDungeonDay(result, "tarro_forest", -1, 1, 0)
                    SV.tarro_forest.dungpoints = SV.tarro_forest.dungpoints + 50
                    SV.tarro_town.apple_tree_get = false
                end
            end
        end
    end
    
end

---deep_tarro_forest.Rescued(zone, name, mail)
--Engine callback function
function deep_tarro_forest.Rescued(zone, name, mail)


end

return deep_tarro_forest

