--[[
    init.lua
    Created: 03/13/2026 18:28:09
    Description: Autogenerated script file for the map HertzWest.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local HertzWest = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzWest.Init(map)
--Engine callback function
function HertzWest.Init(map)
  EXPLCOMMON.AllyFollow(true, true)
end

---HertzWest.Enter(map)
--Engine callback function
function HertzWest.Enter(map)

  GAME:FadeIn(20)

end

---HertzWest.Exit(map)
--Engine callback function
function HertzWest.Exit(map)


end

---HertzWest.Update(map)
--Engine callback function
function HertzWest.Update(map)


end

---HertzWest.GameSave(map)
--Engine callback function
function HertzWest.GameSave(map)


end

---HertzWest.GameLoad(map)
--Engine callback function
function HertzWest.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- Entrances

function HertzWest.ExitE_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzLeftT", "EnterW")
end

function HertzWest.ExitN_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzVault", "EnterS")
end

return HertzWest

