--[[
    init.lua
    Created: 03/13/2026 18:28:09
    Description: Autogenerated script file for the map HertzWest.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.HertzWest.cutscene'

-- Package name
local HertzWest = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzWest.Init(map)
--Engine callback function
function HertzWest.Init(map)
  if West_visit then
    EXPLCOMMON.AllyFollow(true, true)
  else
    Line.Short()
    West_visit = true
  end
end

---HertzWest.Enter(map)
--Engine callback function
function HertzWest.Enter(map)

  GAME:FadeIn(20)

end

---HertzWest.Exit(map)
--Engine callback function
function HertzWest.Exit(map)


end

---HertzWest.Update(map)
--Engine callback function
function HertzWest.Update(map)


end

---HertzWest.GameSave(map)
--Engine callback function
function HertzWest.GameSave(map)


end

---HertzWest.GameLoad(map)
--Engine callback function
function HertzWest.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- Characters

function HertzWest.Cook_Action(obj, activator)
  
end

-- Entrances

function HertzWest.ExitE_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzLeftT", "EnterW")
end

function HertzWest.ExitN_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzVault", "EnterS")
end

return HertzWest

