--[[
    init.lua
    Created: 08/27/2025 21:06:38
    Description: Autogenerated script file for the map AppleTown.
]]
-- Commonly included lua functions and data
require 'origin.common'
require 'explorers_of_friending.ground.AppleTown.cutscene'

-- Package name
local AppleTown = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTown.Init(map)
--Engine callback function
function AppleTown.Init(map)
  COMMON.RespawnAllies()
  GAME:SetCanSwitch(false)
  if SV.guild.day == 1 then
    Apple.Tour()
  end
end

---AppleTown.Enter(map)
--Engine callback function
function AppleTown.Enter(map)

  GAME:FadeIn(20)

end

---AppleTown.Exit(map)
--Engine callback function
function AppleTown.Exit(map)


end

---AppleTown.Update(map)
--Engine callback function
function AppleTown.Update(map)


end

---AppleTown.GameSave(map)
--Engine callback function
function AppleTown.GameSave(map)


end

---AppleTown.GameLoad(map)
--Engine callback function
function AppleTown.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- Characters

local azutalk = 0

function AppleTown.Teammate1_Action(obj, activator)
  local tour = CH("AppleTG")
  COMMON.FaceEachother("PLAYER", "Teammate1")
  if azutalk == 1 then
    COMMON.FaceEachother("PLAYER", "Teammate1")
    COMMON.SetCharAndEmotion(obj, "Inspired")
    UI:WaitShowDialogue("Maru! Imagine how good of a pie mama could make with this!!")

    COMMON.SetCharAndEmotion(obj, "Joyous")
    UI:WaitShowDialogue("Let's bring it back!!")

    COMMON.SetCharAndEmotion(activator, "Stunned")
    UI:WaitShowDialogue("Azu,[pause=30] I think that would be illegal.")

    
    GROUND:CharAnimateTurnTo(obj, Direction.UpRight, 4)
    COMMON.SetCharAndEmotion(obj, "Angry")
    UI:WaitShowDialogue("Hmmph!")
    COMMON.CharHop("Teammate1")
    UI:WaitShowDialogue("No fair...!")
  else
    azutalk = 1
    COMMON.FaceEachother("PLAYER", "Teammate1")
    COMMON.SetCharAndEmotion(tour, "Happy")
    UI:WaitShowDialogue("And this is the favorite, and famous, largest apple to discover.")
    UI:WaitShowDialogue("We hope that by keeping it infused with the ground,[pause=25] we will grow a whole big tree!")

    COMMON.SetCharAndEmotion(obj, "Inspired")
    UI:WaitShowDialogue("Whooaaaaa...!")

    COMMON.SetCharAndEmotion(activator, "Normal")
    UI:WaitShowDialogue("Pretty cool.")
  end
end

function AppleTown.AppleTG_Action(obj, activator)
  local azura = CH("Teammate1")
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("Sir, are you related to the Azurill drooling at the Grand Apple?")

  GROUND:CharTurnToCharAnimated(activator, azura, 4)
  COMMON.SetCharAndEmotion(activator, "Stunned")
  UI:WaitShowDialogue("...um, yeah...?")

  COMMON.SetCharAndEmotion(obj, "Pain")
  UI:WaitShowDialogue("Please control her...")
end

function AppleTown.AppleTownConcertEnter_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTownConcert", "Enter")
end

function AppleTown.AppleTownMayorEnter_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTownMayor", "Enter")
end

function AppleTown.Puff_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("I got in trouble once drooling on the Apple.")
  COMMON.SetCharAndEmotion(obj, "Pain")
  UI:WaitShowDialogue("Never have I ever thought I would get pelted by the one thing I love...!")
end

function AppleTown.Bubba_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("I heard that some of us went to fight in Entoh.")
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("But usually we send out a signal, so maybe it's just a rumor?")
end

function AppleTown.ApplinA_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Happy")
  UI:WaitShowDialogue("Maybe we just missed the signal. Been a while since we've ever had one.")
end

function AppleTown.ApplinB_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("Maybe the fighters just wanted to throw hands.")
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("It's not against us to fight a bunch.")
end

function AppleTown.Chum_Action(obj, activator)
  local rexio = CH("Teammate2")
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("[speed=0.2]...so you want apples...?")

  COMMON.SetCharAndEmotion(rexio, "Angry")
  UI:WaitShowDialogue("Yes![pause=30] Please![pause=60] And I mean, PLEASE!")

  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("[speed=0.1]Well...")
  GROUND:CharAnimateTurnTo(obj, Direction.Left, 12)
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowTimedDialogue("[speed=0.2]...maybe they're...")

  COMMON.CharAngry("Teammate2")
  COMMON.CharHop("Teammate2")
  COMMON.SetCharAndEmotion(rexio, "Shouting")
  UI:WaitShowDialogue("WHERE ARE THEY?!?!")

  GROUND:CharAnimateTurnTo(obj, Direction.DownRight, 12)
  COMMON.SetCharAndEmotion(obj, "Pain")
  UI:WaitShowTimedDialogue("[speed=0.2]Geez, brother.[pause=80] No need to get all feisty.")

  COMMON.FaceEachother("Teammate2", "PLAYER")
  COMMON.SetCharAndEmotion(rexio, "Teary-Eyed")
  UI:WaitShowTimedDialogue("Maru, please...!")

  COMMON.SetCharAndEmotion(activator, "Stunned")
  UI:WaitShowTimedDialogue("I don't think I can help...")

  GROUND:CharAnimateTurnTo(rexio, Direction.UpLeft, 3)
  COMMON.SetCharAndEmotion(rexio, "Pain")
  UI:WaitShowTimedDialogue("Waaa...")

  COMMON.SetCharAndEmotion(activator, "Normal")
  UI:WaitShowTimedDialogue("(I think I'll need to look for the apples before Rexio loses it.)")
end

function AppleTown.Teammate2_Action(obj, activator)
  AppleTown.Chum_Action(obj, activator)
end

return AppleTown

