--[[
    init.lua
    Created: 08/27/2025 21:06:38
    Description: Autogenerated script file for the map AppleTown.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local AppleTown = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTown.Init(map)
--Engine callback function
function AppleTown.Init(map)


end

---AppleTown.Enter(map)
--Engine callback function
function AppleTown.Enter(map)

  GAME:FadeIn(20)

end

---AppleTown.Exit(map)
--Engine callback function
function AppleTown.Exit(map)


end

---AppleTown.Update(map)
--Engine callback function
function AppleTown.Update(map)


end

---AppleTown.GameSave(map)
--Engine callback function
function AppleTown.GameSave(map)


end

---AppleTown.GameLoad(map)
--Engine callback function
function AppleTown.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return AppleTown

