--[[
    init.lua
    Created: 07/03/2025 22:15:17
    Description: Autogenerated script file for the map SwampTown.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.SwampTown.cutscene'

-- Package name
local SwampTown = {}

-------------------------------
-- Map Callbacks
-------------------------------
---SwampTown.Init(map)
--Engine callback function
function SwampTown.Init(map)
  local rexio = CH("PLAYER")
  local wurp = CH("Wurp")
  local snow = CH("Snow")
  local tidy = CH("Tidy")
  local flow = CH("Flow")
  if SV.entoh_town.AdventureChapter < 3 then
    SV.entoh_town.AdventureChapter = 3
    SwampUp.TransferA()
    
  else
    GROUND:Unhide("Tidy")
    GROUND:Unhide("Flow")
    GROUND:Unhide("Snow")
    GROUND:Unhide("Wurp")
    GROUND:CharSetAction(tidy, RogueEssence.Ground.PoseGroundAction(tidy.Position, tidy.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Trip")))

    GROUND:TeleportTo(wurp, 140, 150, Direction.DownLeft, 0)
    GROUND:TeleportTo(snow, 160, 170, Direction.DownLeft, 0)
  end
end

---SwampTown.Enter(map)
--Engine callback function
function SwampTown.Enter(map)

  GAME:FadeIn(20)

end

---SwampTown.Exit(map)
--Engine callback function
function SwampTown.Exit(map)


end

---SwampTown.Update(map)
--Engine callback function
function SwampTown.Update(map)


end

---SwampTown.GameSave(map)
--Engine callback function
function SwampTown.GameSave(map)


end

---SwampTown.GameLoad(map)
--Engine callback function
function SwampTown.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

right_house = -1
flowup = false
local answer = false

function SwampTown.Mud_Action(obj, activator)
  UI:SetSpeaker(CH("Mud"))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowTimedDialogue("Mud!", 60)

  UI:SetSpeaker(CH("Kip"))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowTimedDialogue("Kip!", 40)

  UI:SetSpeaker(CH("Mud"))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowTimedDialogue("Mud!", 60)

  UI:SetSpeaker(CH("Kip"))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowTimedDialogue("Kip!", 45)
end

function SwampTown.Kip_Action()
  SwampTown.Mud_Action()
end

function SwampTown.Poli_Action(obj, activator)
  UI:SetSpeaker(CH("Poli"))
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("I love this show!")
end

function SwampTown.Snow_Action(obj, activator)
  COMMON.FaceEachother("PLAYER", "Snow")
  UI:SetSpeaker(CH("Snow"))
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("I-... I don't get it...")
end

function SwampTown.Marshal_Action(obj, activator)
  local rexio = CH("PLAYER")
  local marsh = CH("Marshal")
  COMMON.FaceEachother("PLAYER", "Marshal")

  if right_house == -1 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oi, moit. The boss is awaitin' for ya.")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Okay...?[pause=10] Where are they?")

    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Get this:[pause=30] in the house[pause=20] that [emote=Happy]isn't the one onna left.")
    right_house = 1
  elseif right_house == 5.1 then
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Yeah mate, um, what was the third house ya tried...?")

    local choices = {("Left"),
        ("Right")}
    UI:BeginChoiceMenu("It's a fifty-fifty, so if ya aren't sure, just guess again, yeah?", choices, 1, 2)
    UI:WaitForChoice()
    result = UI:ChoiceResult()
    if answer == false then
      answer = true
      if result == 1 then
        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Happy")
        UI:WaitShowDialogue("Yeah. You're bright on, mate. Boss is in that house.")

        UI:SetSpeaker(rexio)
        UI:SetSpeakerEmotion("Stunned")
        UI:WaitShowDialogue("Great.[pause=30] Why didn't you just tell me that?")

        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("...boss's orders.")
        UI:WaitShowDialogue("First try answer, take somethin' from me wasting ya time.")

        GAME:GivePlayerItem("berry_oran")
        SOUND:PlayFanfare("Fanfare/Item")
        UI:ResetSpeaker()
        UI:WaitShowDialogue("Marshal gives Rexio an Oran Berry.")
        right_house = 6
      else
        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Happy")
        UI:WaitShowDialogue("Nah, mate. But now ya know.")
      end
    else
      if result == 1 then
        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Happy")
        UI:WaitShowDialogue("Yeah. You're bright on, mate. Boss is in that house.")

        UI:SetSpeaker(rexio)
        UI:SetSpeakerEmotion("Stunned")
        UI:WaitShowDialogue("Great.[pause=30] Why didn't you just tell me that?")

        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("...boss's orders.")
        right_house = 6
      else
        UI:SetSpeaker(marsh)
        UI:SetSpeakerEmotion("Happy")
        UI:WaitShowDialogue("Nah, mate. You should've known.")
      end
    end    
  end
end

function SwampTown.Tidy_Action(obj, activator)
  UI:SetSpeaker(CH("Tidy"))
  UI:SetSpeakerEmotion("Dizzy")
  UI:WaitShowTimedDialogue(".....................", 60)

  UI:SetSpeaker(CH("Flow"))
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Just... give her a second.")
end

function SwampTown.Flow_Action(obj, activator)
  UI:SetSpeaker(CH("Flow"))
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("When this is all over, I'm gonna need a new flower...")
end

function SwampTown.Wurp_Action(obj, activator)
  UI:SetSpeaker(CH("Wurp"))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("A stwange fowm of awt that many diffwint civiwians have taken as their own.")

  UI:SetSpeaker(CH("Wurp"))
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("It'w take a moment to appweciate it fuwwy.")
end

function SwampTown.LHouse_Touch(obj, activator)
  local rexio = CH("PLAYER")
  local marsh = CH("Marshal")
  if right_house == -1 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Ooooiiiiii!")

    COMMON.FaceEachother("PLAYER", "Marshal")
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("What?")

    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Ya can't just enter houses without permission, mate!")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Speak ta me, first.")
  elseif right_house == 2 then
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowTimedDialogue("Hold on...", 50)

    COMMON.FaceEachother("PLAYER", "Marshal")
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Nah, ya fine.")
    right_house = 3
  elseif right_house == 3 then
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowTimedDialogue("Aw no! It's terrible!", 90)

    COMMON.FaceEachother("PLAYER", "Marshal")
    GAME:WaitFrames(40)
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("It's the one on the right.")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("...")
    right_house = 4
  elseif right_house == 5 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("A-actually, just... come back to me, mate.")

    COMMON.FaceEachother("PLAYER", "Marshal")
    right_house = 5.1
  elseif right_house == 6 then
    SwampUp.TransferB()
  end
end

function SwampTown.RHouse_Touch(obj, activator)
  local rexio = CH("PLAYER")
  local marsh = CH("Marshal")
  if right_house == -1 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Ooooiiiiii!")

    COMMON.FaceEachother("PLAYER", "Marshal")
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("What?")

    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Ya can't just enter houses without permission, mate!")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Speak ta me, first.")
  elseif right_house == 1 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("...aw, actually, mate.")

    COMMON.FaceEachother("PLAYER", "Marshal")
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("What now?")

    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Probably... actually is the one on the left.")
    right_house = 2
  elseif right_house == 4 then 
    UI:SetSpeaker(marsh)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Left.")

    COMMON.FaceEachother("PLAYER", "Marshal")
    GAME:WaitFrames(90)
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("...")
    right_house = 5
  end
end

function SwampTown.Exit_Touch(obj, activator)
  local rexio = CH("PLAYER")
  if right_house < 7 then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(I'll need to figure how to get everyone back home first.)")
    GROUND:AnimateToPosition(rexio, "Walk", Dir8.Left, rexio.Position.X - 20, rexio.Position.Y, 1, 1, 0)
  end
end

function SwampTown.flowposition_Touch(obj, activator)
  if flowup == false then
    flowup = true
    UI:SetSpeaker(CH("Flow"))
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Hey, Rexio,[pause=10] before you go,[pause=10] can you figure out how to get us out of here?")
    UI:WaitShowDialogue("Looks like the dungeon is a one way trip and the stairs back lead to a dead end...")

    UI:SetSpeaker(CH("PLAYER"))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("I gotchu.")
  end
end

function SwampTown.DungeonExit_Touch(obj, activator)
  COMMON.UnlockWithFanfare("swamp_line", false)
  local dungeon_entrances = {"swamp_line"}
  local ground_entrances = {}
  COMMON.ShowDestinationMenu(dungeon_entrances, ground_entrances)
end
return SwampTown

