--[[
    init.lua
    Created: 07/03/2025 22:15:17
    Description: Autogenerated script file for the map SwampTown.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local SwampTown = {}

-------------------------------
-- Map Callbacks
-------------------------------
---SwampTown.Init(map)
--Engine callback function
function SwampTown.Init(map)


end

---SwampTown.Enter(map)
--Engine callback function
function SwampTown.Enter(map)

  GAME:FadeIn(20)

end

---SwampTown.Exit(map)
--Engine callback function
function SwampTown.Exit(map)


end

---SwampTown.Update(map)
--Engine callback function
function SwampTown.Update(map)


end

---SwampTown.GameSave(map)
--Engine callback function
function SwampTown.GameSave(map)


end

---SwampTown.GameLoad(map)
--Engine callback function
function SwampTown.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return SwampTown

