--[[
    init.lua
    Created: 05/15/2026 20:52:33
    Description: Autogenerated script file for the map Osias.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.Osias.cutscene'

-- Package name
local Osias = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Osias.Init(map)
--Engine callback function
function Osias.Init(map)
  if SV.Story.sect == 2 then
    Dreset.Guild()
  else
    EXPLCOMMON.TeleportToMarker(CH("Emburst"), "Flared", Dir8.DownLeft)
  end
end

---Osias.Enter(map)
--Engine callback function
function Osias.Enter(map)

  GAME:FadeIn(20)

end

---Osias.Exit(map)
--Engine callback function
function Osias.Exit(map)


end

---Osias.Update(map)
--Engine callback function
function Osias.Update(map)
  Partner()
end

---Osias.GameSave(map)
--Engine callback function
function Osias.GameSave(map)


end

---Osias.GameLoad(map)
--Engine callback function
function Osias.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function Osias.ExitN_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("OsiasLake", "EnterS")
end

function Osias.ExitS_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzGuildOut", "EnterN")
end

function Osias.ExitE_Touch(obj, activator)
  --EXPLCOMMON.FadeEnterGround("HertzGuildOut", "EnterN")
end

function Osias.ExitW_Touch(obj, activator)
  --EXPLCOMMON.FadeEnterGround("HertzGuildOut", "EnterN")
end

function Osias.Emburst_Action(obj, activator)
  EXPLCOMMON.FaceEachother(obj, activator)

  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("...I'm not the guildmaster, kids.")
end

return Osias

