--[[
    init.lua
    Created: 11/03/2025 09:35:15
    Description: Autogenerated script file for the map DesertN.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local DesertN = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DesertN.Init(map)
--Engine callback function
function DesertN.Init(map)
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  GROUND:TeleportTo(CH("Teammate1"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  GROUND:TeleportTo(CH("Teammate2"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.UpRight, 0)
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
end

---DesertN.Enter(map)
--Engine callback function
function DesertN.Enter(map)

  GAME:FadeIn(20)

end

---DesertN.Exit(map)
--Engine callback function
function DesertN.Exit(map)


end

---DesertN.Update(map)
--Engine callback function
function DesertN.Update(map)


end

---DesertN.GameSave(map)
--Engine callback function
function DesertN.GameSave(map)


end

---DesertN.GameLoad(map)
--Engine callback function
function DesertN.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- Characters

function DesertN.HertzTunnel_Touch(obj, activator)
  
end

-- Entrances

function DesertN.W_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertNW", "EastEnter")
end

function DesertN.SW_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertSW", "NorthEastEnter")
end

function DesertN.S_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertS", "NorthEnter")
end

function DesertN.SE_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertSE", "NorthWestEnter")
end

function DesertN.E_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertNE", "WestEnter")
end

function DesertN.N_Touch(obj, activator)
  COMMON.FadeEnterGround("HertzGate", "Enter")
end

return DesertN

