--[[
    init.lua
    Created: 03/03/2025 23:56:07
    Description: Autogenerated script file for the map TheField.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local TheField = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TheField.Init(map)
--Engine callback function
function TheField.Init(map)
  COMMON.RespawnAllies()
  if SV.tarro_town.DarknessChapter == 3 then
    TheField.First()
  end
  MapStrings = STRINGS.MapStrings
  local partner = CH('Teammate1')  
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true
end

---TheField.Enter(map)
--Engine callback function
function TheField.Enter(map)

  GAME:FadeIn(20)

end

---TheField.Exit(map)
--Engine callback function
function TheField.Exit(map)


end

---TheField.Update(map)
--Engine callback function
function TheField.Update(map)
  
end

---TheField.GameSave(map)
--Engine callback function
function TheField.GameSave(map)


end

---TheField.GameLoad(map)
--Engine callback function
function TheField.GameLoad(map)

  GAME:FadeIn(20)

end

function TheField.First()
  local maru = CH("PLAYER")
  local azura = CH("Teammate1")
  local zoomer = CH("Zoomer")  
  GAME:CutsceneMode(true)
  local coro3 = TASK:BranchCoroutine(function() 
    GROUND:MoveInDirection(maru, Dir8.Up, 40, false, 2)
    end)	
  local coro4 = TASK:BranchCoroutine(function() 
    GROUND:MoveInDirection(zoomer, Dir8.Up, 30, false, 2)
    UI:SetSpeaker(zoomer)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Alright, I'm done helping you, two.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oi! Boss! They're here!")
    end)
  local coro5 = TASK:BranchCoroutine(function() 
    GAME:WaitFrames(25)
    GROUND:MoveInDirection(azura, Dir8.Up, 40, false, 2)
    end)
  local coro6 = TASK:BranchCoroutine(function()
    GAME:FadeIn(50)
    end)
  TASK:JoinCoroutines({coro3, coro4, coro5, coro6})
  Zoommove = true
  GROUND:MoveInDirection(zoomer, Dir8.Up, 60, false, 4)
  
  GROUND:TeleportTo(zoomer, smear.Position.X - 300, smear.Position.Y, Dir8.DownRight, 2)
  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Let's go.")
  GAME:CutsceneMode(false)
end

-------------------------------
-- Entities Callbacks
-------------------------------
function TheField.SceneEnd_Touch(obj, activator)
  local maru = CH("PLAYER")
  local smear = CH("Smear")
  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Um... we're here about the letter...")

  GAME:FadeOut(false, 90)

  UI:ResetSpeaker()
  UI:WaitShowDialogue("And to you two,[pause=65] I say:[pause=45] \"Welcome!\"")
end

return TheField

