--[[
    init.lua
    Created: 03/03/2025 23:56:07
    Description: Autogenerated script file for the map TheField.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local TheField = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TheField.Init(map)
--Engine callback function
function TheField.Init(map)
  COMMON.RespawnAllies()
  if SV.tarro_town.DarknessChapter == 3 then
    TheField.First()
  end
  MapStrings = STRINGS.MapStrings
  local partner = CH('Teammate1')  
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true
end

---TheField.Enter(map)
--Engine callback function
function TheField.Enter(map)

  GAME:FadeIn(20)

end

---TheField.Exit(map)
--Engine callback function
function TheField.Exit(map)


end

---TheField.Update(map)
--Engine callback function
function TheField.Update(map)
  
end

---TheField.GameSave(map)
--Engine callback function
function TheField.GameSave(map)


end

---TheField.GameLoad(map)
--Engine callback function
function TheField.GameLoad(map)

  GAME:FadeIn(20)

end

function TheField.First()
  local maru = CH("PLAYER")
  local azura = CH("Teammate1")
  local zoomer = CH("Zoomer")
  local smear = CH("Smear") 
  GAME:CutsceneMode(true)
  local coro3 = TASK:BranchCoroutine(function() 
    GROUND:MoveInDirection(maru, Dir8.Up, 40, false, 2)
    end)	
  local coro4 = TASK:BranchCoroutine(function() 
    GROUND:MoveInDirection(zoomer, Dir8.Up, 30, false, 2)
    UI:SetSpeaker(zoomer)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Alright, I'm done helping you, two.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Oi! Boss! They're here!")
    end)
  local coro5 = TASK:BranchCoroutine(function() 
    GAME:WaitFrames(25)
    GROUND:MoveInDirection(azura, Dir8.Up, 40, false, 2)
    end)
  local coro6 = TASK:BranchCoroutine(function()
    GAME:FadeIn(50)
    end)
  TASK:JoinCoroutines({coro3, coro4, coro5, coro6})
  Zoommove = true
  GROUND:MoveInDirection(zoomer, Dir8.Up, 60, false, 4)
  
  GROUND:TeleportTo(zoomer, smear.Position.X - 200, smear.Position.Y, Dir8.DownRight, 2)
  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Let's go.")
  GAME:CutsceneMode(false)
end

-------------------------------
-- Entities Callbacks
-------------------------------
function TheField.SceneEnd_Touch(obj, activator)
  local maru = CH("PLAYER")
  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Um... we're here about the letter...")

  GAME:FadeOut(false, 90)

  UI:ResetSpeaker()
  UI:WaitShowDialogue("And to you two,[pause=65] I say:[pause=45] \"Welcome!\"")
  --Begin replacement
  --Save Maru and Azura's stats
  SV.guilders.tarro_town.bluetail_stats = GAME:GetPlayerPartyTable()
  --Replace them with Rexio
  GAME:RemovePlayerTeam(0)
  GAME:RemovePlayerTeam(0)
  local mon_id = RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Male)

  local p = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 5, "", 0)
  p.IsFounder = true
  p.IsPartner = true
  p.Nickname = "Rexio"

  _DATA.Save.ActiveTeam.Players:Add(p)
  SV.guilders.tarro_town.bluetail_storage = {}
  --remove bag and storage items and put them in a temporary table
  GAME:DepositAll()
  --[[local storage = _DATA.Save.ActiveTeam.Storage
  local count = storage.Keys.Count
  for i = count - 1, 0, -1 do
    print(storage.Keys[i])
    local slot = {id = storage.Keys[i], count = storage.Values[i], hidden = ""} --checks ID, the amount of said item, and any hidden value.
    table.insert(SV.guilders.tarro_town.bluetail_storage, slot) --puts it into a storage slot in the table variable.
    storage.Remove(storage.Keys[i]) --removes it from storage
  end]]--
  local box_storage = _DATA.Save.ActiveTeam.BoxStorage
  local box_count = box_storage.Count
  if box_count > 1 then
    for i = box_count - 1, 0, -1 do
      local slot = {id = box_storage[i].ID, count = 1, hidden_value = box_storage[i].HiddenValue}
      table.insert(SV.guilders.tarro_town.bluetail_storage, slot)
      box_storage.RemoveAt(i)
    end
  end

  GAME:EnterGroundMap("entoh_town", "RexioHome", "RexioStart")
end

return TheField

