--[[
    init.lua
    Created: 12/11/2025 11:20:44
    Description: Autogenerated script file for the map HertzEntrance.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.HertzEntrance.cutscene'

local Coro = function()
  local gonk = CH("Gonk")
  if go_in == true and Golmoved == false then
    GROUND:Hide("hall2")
    GROUND:MoveToMarker(gonk, MRKR("move1"), false, 1)
    GROUND:MoveToMarker(gonk, MRKR("move2"), false, 1)
    GROUND:CharAnimateTurnTo(gonk, Dir8.Right, 2)
    Golmoved = true
    GROUND:Unhide("hall2")
  elseif go_in == false and Golmoved == true then
    GROUND:Hide("hall2")
    GROUND:MoveToMarker(gonk, MRKR("move1"), false, 1)
    GROUND:MoveToMarker(gonk, MRKR("move3"), false, 1)
    GROUND:CharAnimateTurnTo(gonk, Dir8.Down, 2)
    Golmoved = false
    GROUND:Unhide("hall2")
  end
end

-- Package name
local HertzEntrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzEntrance.Init(map)
--Engine callback function
function HertzEntrance.Init(map)
  go_in = false
  Golmoved = false
  if SV.guild.time == 10 then
    HertzTown.Cooldown()
    SV.guild.time = 11
  else
    COMMON.ThreeTeam()
  end
end

---HertzEntrance.Enter(map)
--Engine callback function
function HertzEntrance.Enter(map)

  GAME:FadeIn(20)

end

---HertzEntrance.Exit(map)
--Engine callback function
function HertzEntrance.Exit(map)


end

---HertzEntrance.Update(map)
--Engine callback function
function HertzEntrance.Update(map)
  Partner()
  TASK:StartEntityTask(CH("Gonk"), Coro)
end

---HertzEntrance.GameSave(map)
--Engine callback function
function HertzEntrance.GameSave(map)


end

---HertzEntrance.GameLoad(map)
--Engine callback function
function HertzEntrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function HertzEntrance.EntranceEnter_Touch(obj, activator)
  COMMON.FadeEnterGround("HertzEntrance", "ent_Enter")
end

function HertzEntrance.TownExit_Touch(obj, activator)
  COMMON.FadeEnterGround("HertzGate", "GateEnter")
end

function HertzEntrance.CenterEnter_Touch(obj, activator)
  COMMON.FadeEnterGround("HertzCenter", "EnterS")
end

function HertzEntrance.Kazen_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("Good day to you, my name is Kazen; welcome to my fast travel service.")
  if SV.hertz_town.fastvisited[1] == 1 then
    UI:WaitShowDialogue("Would you like to go to " .. SV.hertz_town.fastvisited[1])
  elseif SV.hertz_town.fastvisited[1] < 1 then
    UI:WaitShowDialogue("Looks like you haven't even gone into town yet. There's no need for me to assist you.")
  end
end

function HertzEntrance.Storage_Action(obj, activator)
  COMMON.ShowTeamStorageMenu()
end

function HertzEntrance.Gonk_Action(obj, activator)
  if CH("PLAYER").Position.Y >= CH("Gonk").Position.Y then
    if SV.hertz_town.passcount == 0 then
      COMMON.SetCharAndEmotion(obj, "Normal")
      UI:WaitShowDialogue("[speed=0.5]You do not seem to be holding a pass. I cannot let you through.")
    else
      COMMON.SetCharAndEmotion(obj, "Happy")
      UI:WaitShowDialogue("[speed=0.5]You do seem to be holding a pass. I can let you through.")

      UI:ResetSpeaker()
      local choices = {
        ("Yes!"),
        ("No!")
      }
      UI:BeginChoiceMenu("Hand the pass over?", choices, 1, 2)
      UI:WaitForChoice()
      result = UI:ChoiceResult()
      if result == 1 then
        COMMON.SetCharAndEmotion(obj, "Normal")
        UI:WaitShowDialogue("[speed=0.5]You may enter.")
        go_in = true

        GAME:WaitFrames(50)
        COMMON.SetCharAndEmotion(activator, "Happy")
        UI:WaitShowDialogue("Alright, let's go.")
      end
    end
  else
    local talk = math.random(2)
    if talk == 1 then
      COMMON.SetCharAndEmotion(obj, "Normal")
      UI:WaitShowDialogue("[speed=0.5]If it isn't too much to ask, if the thief you're talking about did happen to get in.")
      UI:WaitShowDialogue("[speed=0.5]Please report it to me...[pause=45][emote=Stunned] and no one else.")
    else
      COMMON.SetCharAndEmotion(obj, "Normal")
      UI:WaitShowDialogue("[speed=0.5]Well, go on.")
      UI:WaitShowDialogue("[speed=0.5]I'm not in the way.")
    end
  end
end

function HertzEntrance.ShopA_Touch(obj, activator)
  COMMON.FadeEnterGround("HertzShopsA", "Enter")
end

function HertzEntrance.hall2_Touch(obj, activator)
  if obj.Position.Y < activator.Position.Y then
    go_in = false
  elseif obj.Position.Y > activator.Position.Y then
    go_in = true
  end
end

return HertzEntrance

