--[[
    init.lua
    Created: 03/19/2025 16:43:13
    Description: Autogenerated script file for the map entoh_town.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local entoh_town = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---entoh_town.Init(zone)
--Engine callback function
function entoh_town.Init(zone)
    Endsouthboss = false
end

---entoh_town.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function entoh_town.EnterSegment(zone, rescuing, segmentID, mapID)
    
end

---entoh_town.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function entoh_town.ExitSegment(zone, result, rescue, segmentID, mapID)
    GAME:EnterZone("entoh_town", -1, 11, 0)
end

---entoh_town.Rescued(zone, name, mail)
--Engine callback function
function entoh_town.Rescued(zone, name, mail)


end

return entoh_town

