--[[
    init.lua
    Created: 09/11/2024 13:50:11
    Description: Autogenerated script file for the map tarro_tree_hollows.
]]--
-- Commonly included lua functions and data
--require 'origin.common'
require 'explorers_of_friending.common'
require 'explorers_of_friending.event_battle'

-- Package name
local tarro_tree_hollows = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---tarro_tree_hollows.Init(zone)
--Engine callback function
function tarro_tree_hollows.Init(zone)
    
end

---tarro_tree_hollows.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function tarro_tree_hollows.EnterSegment(zone, rescuing, segmentID, mapID)


end

---tarro_tree_hollows.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function tarro_tree_hollows.ExitSegment(zone, result, rescue, segmentID, mapID)
  if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    if segmentID == 0 then
      SV.tarro_town.PieChapter = 8
      GAME:EnterZone("tarro_town", -1, 3, 0)
    end
  else
    if segmentID == 0 then
      SV.tarro_tree_hollows.entering_party = GAME:GetPlayerPartyTable()
      if SV.tarro_town.PieChapter == 7 then
        GAME:RemovePlayerTeam(2)
        GAME:RemovePlayerTeam(2)
        GAME:RemovePlayerTeam(2)
        SV.tarro_town.PieChapter = 8
      end
      GAME:EnterZone("tarro_tree_hollows", -1, 0, 0)
    else
      GAME:EndDungeonRun(result, "tarro_tree_hollows", -1, 0, 0, false, true)
    end
  end
end

---tarro_tree_hollows.Rescued(zone, name, mail)
--Engine callback function
function tarro_tree_hollows.Rescued(zone, name, mail)


end

return tarro_tree_hollows

