--[[
    init.lua
    Created: 09/18/2024 13:37:43
    Description: Autogenerated script file for the map TarroTownBigTree_ch3.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local TarroTownBigTree_ch3 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownBigTree_ch3.Init(map)
--Engine callback function
function TarroTownBigTree_ch3.Init(map)
  --SV.tarro_town.PieChapter == 7 is the first cutscene
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true

end

---TarroTownBigTree_ch3.Enter(map)
--Engine callback function
function TarroTownBigTree_ch3.Enter(map)

  GAME:FadeIn(20)

end

---TarroTownBigTree_ch3.Exit(map)
--Engine callback function
function TarroTownBigTree_ch3.Exit(map)


end

---TarroTownBigTree_ch3.Update(map)
--Engine callback function
function TarroTownBigTree_ch3.Update(map)


end

---TarroTownBigTree_ch3.GameSave(map)
--Engine callback function
function TarroTownBigTree_ch3.GameSave(map)


end

---TarroTownBigTree_ch3.GameLoad(map)
--Engine callback function
function TarroTownBigTree_ch3.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function TarroTownBigTree_ch3.TreeHallow_Entrance_Touch(obj, activator)
  --[[COMMON.UnlockWithFanfare("tarro_tree_hollows", false)
  local dungeon_entrances = {"tarro_tree_hollows"}
  local ground_entrances = {}
  COMMON.ShowDestinationMenu(dungeon_entrances, ground_entrances)]]--
end

function TarroTownBigTree_ch3.InfoSign_Action(obj, activator)
  UI:ResetSpeaker()
  UI:WaitShowDialogue("Today's news!:")
  UI:WaitShowDialogue("The mayor is looking for more recruits to carry her honey around.")
  UI:WaitShowDialogue("Payment will be done bihourly by Queen herself.")
  UI:WaitShowDialogue("All help is welcome! Please apply at the hive west of town!")
end

function TarroTownBigTree_ch3.Tree_2ndFloorEntrance_Touch(obj, activator)
  
end

function TarroTownBigTree_ch3.PurpKek_Counter_Action(obj, activator)

end

function TarroTownBigTree_ch3.Tree_Exit_Touch(obj, activator)
  outside_enter = 4
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("tarro_town", "TarroTownSquare_ch3", "TarroTree_Exit")
end

function TarroTownBigTree_ch3.Hollian_Action(obj, activator)
  local holly = CH("Hollian")

  UI:SetSpeaker(holly)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Sorry, the dungeon is only authorized to those equal to or higher than rescue teams.")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("It's been done as word of an explosion went around from the kids.")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Don't know why we're listening to them[pause=35], [emote=Normal]but the issue is being investigated..")
end

function TarroTownBigTree_ch3.Storage_Action(obj, activator)
  COMMON:ShowTeamStorageMenu()
end

function TarroTownBigTree_ch3.Archia_Action(obj, activator)
  local archia = CH("Archia")

  UI:SetSpeaker(archia)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Gosh, they sure are taking a while on that second floor...")
end

return TarroTownBigTree_ch3

