--[[
    init.lua
    Created: 12/11/2025 11:20:44
    Description: Autogenerated script file for the map HertzLeftT.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local HertzLeftT = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzLeftT.Init(map)
--Engine callback function
function HertzLeftT.Init(map)
  EXPLCOMMON.ThreeTeam()
end

---HertzLeftT.Enter(map)
--Engine callback function
function HertzLeftT.Enter(map)

  GAME:FadeIn(20)

end

---HertzLeftT.Exit(map)
--Engine callback function
function HertzLeftT.Exit(map)


end

---HertzLeftT.Update(map)
--Engine callback function
function HertzLeftT.Update(map)

end

---HertzLeftT.GameSave(map)
--Engine callback function
function HertzLeftT.GameSave(map)


end

---HertzLeftT.GameLoad(map)
--Engine callback function
function HertzLeftT.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function HertzLeftT.ExitW_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzWest", "EnterE")
end

function HertzLeftT.ExitE_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzCenter", "EnterW")
end

function HertzLeftT.Kazen_Action(obj, activator)
  EXPLCOMMON.KazenService()
end

function HertzLeftT.Secret_Touch(obj, activator)
  GAME:EnterDungeon("dane_desert", 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, false, false)
end

return HertzLeftT

