--[[
    init.lua
    Created: 10/31/2025 14:43:22
    Description: Autogenerated script file for the map DesertNE.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local DesertNE = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DesertNE.Init(map)
--Engine callback function
function DesertNE.Init(map)
  COMMON.RespawnAllies()
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  GROUND:TeleportTo(CH("Teammate1"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  GROUND:TeleportTo(CH("Teammate2"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.UpRight, 0)
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
  GROUND:CharSetAnim(CH("Sprout"), "Sleep", true)
end

---DesertNE.Enter(map)
--Engine callback function
function DesertNE.Enter(map)

  GAME:FadeIn(20)

end

---DesertNE.Exit(map)
--Engine callback function
function DesertNE.Exit(map)


end

---DesertNE.Update(map)
--Engine callback function
function DesertNE.Update(map)
  Partner()
end

---DesertNE.GameSave(map)
--Engine callback function
function DesertNE.GameSave(map)


end

---DesertNE.GameLoad(map)
--Engine callback function
function DesertNE.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function DesertNE.Sprout_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Dizzy")
  UI:WaitShowDialogue("[speed=0.2]Water...[pause=45] water...!")

  COMMON.SetCharAndEmotion(GAME:GetPlayerPartyMember(1), "Stunned")
  UI:WaitShowDialogue("Why is he here...?")
  COMMON.SetCharAndEmotion(GAME:GetPlayerPartyMember(2), "Stunned")
  UI:WaitShowDialogue("Who is this...?")
  COMMON.SetCharAndEmotion(GAME:GetPlayerPartyMember(0), "Stunned")
  UI:WaitShowDialogue("We'll come back later.")
end

function DesertNE.cactus1_Action(obj, activator)
  if activator.Nickname == "Rexio" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(Cactus... tall.)")
  elseif activator.Nickname == "Maru" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(These shapes do seem kind of familiar, though.)")
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(One!)")
  end
end

-- Exits

function DesertNE.S_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertSE", "NorthEnter")
end

function DesertNE.SW_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertS", "NorthEastEnter")
end

function DesertNE.W_Touch(obj, activator)
  COMMON.FadeEnterGround("DesertN", "EastEnter")
end

return DesertNE

