--[[
    init.lua
    Created: 09/22/2025 15:53:49
    Description: Autogenerated script file for the map MayorRoom.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.MayorRoom.cutscene'

-- Package name
local MayorRoom = {}
local time = 0

local function wait()
  local maru = CH("PLAYER")
  local azura = CH("Teammate1")
  local rexio = CH("Teammate2")

  time = time + 1
  if time == 600 then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("What are you doing, Blue?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("There's nothing in here, so let's go.")
  end

  if time == 1400 then
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("...okay, maybe you're right.")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("I would've looked under the big pillow, but we can leave, too.")
  end

  if time == 2500 then
    GROUND:Hide("MayorLeave")
    GAME:CutsceneMode(true)
    rexio.CollisionDisabled = true
    maru.CollisionDisabled = true
    COMMON.CharAngry("Teammate2")
    COMMON.FaceEachother(maru, rexio)
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("...")

    GROUND:MoveToPosition(rexio, maru.Position.X, maru.Position.Y + 16, true, 9)

    local coro01 = TASK:BranchCoroutine(function()
      GROUND:MoveToPosition(maru, 214, 350, true, 2)
      end)	
    local coro02 = TASK:BranchCoroutine(function()
      GROUND:MoveToPosition(rexio, 214, 350 + 16, true, 2)
      end)
    local coro03 = TASK:BranchCoroutine(function()
      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Stunned")
      UI:WaitShowTimedDialogue("Welp, okay, alright, we're going then.", 70)
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowTimedDialogue("I,[pause=15] uh,[pause=30] almost found an apple.", 70)

      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Sigh")
      UI:WaitShowDialogue("Whatever, dude.")
      end)
    local coro04 = TASK:BranchCoroutine(function()
      GAME:WaitFrames(95)
      COMMON.CharSweatdrop("Teammate1")
      GAME:WaitFrames(20)
      GROUND:MoveToPosition(azura, 214, 350 + 16, true, 2)
      end)
    local coro04 = TASK:BranchCoroutine(function()
      GAME:WaitFrames(195)
      GAME:FadeOut(false, 90)
      end)  
    TASK:JoinCoroutines({coro01, coro02, coro03, coro04})
    GAME:CutsceneMode(false)
    GAME:EnterGroundMap("AppleMayor_pt2", "Enter")
  end
end

-------------------------------
-- Map Callbacks
-------------------------------
---MayorRoom.Init(map)
--Engine callback function
function MayorRoom.Init(map)
  COMMON.RespawnAllies()
  if SV.guild.time < 40 then
    Mayor.Intro()
  else
    Mayor.Ender()
  end
end

---MayorRoom.Enter(map)
--Engine callback function
function MayorRoom.Enter(map)

end

---MayorRoom.Exit(map)
--Engine callback function
function MayorRoom.Exit(map)


end

---MayorRoom.Update(map)
--Engine callback function
function MayorRoom.Update(map)
  TASK:StartEntityTask(CH("PLAYER"), wait)
end

---MayorRoom.GameSave(map)
--Engine callback function
function MayorRoom.GameSave(map)


end

---MayorRoom.GameLoad(map)
--Engine callback function
function MayorRoom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function MayorRoom.MayorLeave_Touch(obj, activator)
  GAME:EnterGroundMap("AppleTownMayor_pt2", "Enter")
end

return MayorRoom

