--[[
    init.lua
    Created: 12/29/2024 18:48:25
    Description: Autogenerated script file for the map TarroTownTreetop.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local TarroTownTreetop = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownTreetop.Init(map)
--Engine callback function
function TarroTownTreetop.Init(map)


end

---TarroTownTreetop.Enter(map)
--Engine callback function
function TarroTownTreetop.Enter(map)

  GAME:FadeIn(20)

end

---TarroTownTreetop.Exit(map)
--Engine callback function
function TarroTownTreetop.Exit(map)


end

---TarroTownTreetop.Update(map)
--Engine callback function
function TarroTownTreetop.Update(map)


end

---TarroTownTreetop.GameSave(map)
--Engine callback function
function TarroTownTreetop.GameSave(map)


end

---TarroTownTreetop.GameLoad(map)
--Engine callback function
function TarroTownTreetop.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return TarroTownTreetop

