--[[
    init.lua
    Created: 03/08/2025 23:56:33
    Description: Autogenerated script file for the map RexioHome.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'explorers_of_friending.ground.RexioHome.cutscene'

-- Package name
local RexioHome = {}

-------------------------------
-- Map Callbacks
-------------------------------
---RexioHome.Init(map)
--Engine callback function
function RexioHome.Init(map)

  if SV.entoh_town.HelperChapter == -1 then
    Aurm.Feeling()
  elseif SV.entoh_town.package_received == true then
    Aurm.Home()
  end
  
end

---RexioHome.Enter(map)
--Engine callback function
function RexioHome.Enter(map)

  if SV.entoh_town.HelperChapter == -1 then
    
  else
    GAME:FadeIn(20)
  end
  

end

---RexioHome.Exit(map)
--Engine callback function
function RexioHome.Exit(map)


end

---RexioHome.Update(map)
--Engine callback function
function RexioHome.Update(map)


end

---RexioHome.GameSave(map)
--Engine callback function
function RexioHome.GameSave(map)


end

---RexioHome.GameLoad(map)
--Engine callback function
function RexioHome.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function RexioHome.ApartmentEnter_Touch(obj, activator)
  GAME:EnterGroundMap("EntohTownCenter", "HomeMarker")
end

function RexioHome.Poster_Action(obj, activator)
  local rexio = CH("PLAYER")

  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("(This poster of dad is 10 times cooler with me on it.)")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(We have to get another one, our walls are lacking.)")
end

function RexioHome.Luke_Action(obj, activator)
  local rexio = CH("PLAYER")
  local luke = CH("Luke")
  COMMON.FaceEachother("Luke", "PLAYER")
  UI:SetSpeaker(luke)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Go on, Rexio. [pause=30]Don't [emote=Happy]let me stop you.")

  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Feel free to, actually.")

  UI:SetSpeaker(luke)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Rexio.")

  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Kidding, kidding.")
end

return RexioHome

