--[[
    init.lua
    Created: 09/21/2025 23:31:45
    Description: Autogenerated script file for the map AppleMayor.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.AppleMayor.cutscene'

-- Package name
local AppleMayor = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleMayor.Init(map)
--Engine callback function
function AppleMayor.Init(map)
  if SV.guild.day > 1 then
    COMMON.RespawnAllies()
  end
end

---AppleMayor.Enter(map)
--Engine callback function
function AppleMayor.Enter(map)

  GAME:FadeIn(20)

end

---AppleMayor.Exit(map)
--Engine callback function
function AppleMayor.Exit(map)


end

---AppleMayor.Update(map)
--Engine callback function
function AppleMayor.Update(map)


end

---AppleMayor.GameSave(map)
--Engine callback function
function AppleMayor.GameSave(map)


end

---AppleMayor.GameLoad(map)
--Engine callback function
function AppleMayor.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function AppleMayor.Lightning_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("[speed=1.5]Biggy big place for a biggy big mayor.[pause=40] [emote=Worried]He isn't here yet, though.[pause=40] [emote=Happy]It's been a biggy big while.")
end

function AppleMayor.Undrei_Action(obj, activator)
  COMMON.FaceEachother(activator, obj)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("My ozer heads makes goot puppetry, ja?[pause=30] [emote=Happy]Good for the kids.")
end

function AppleMayor.MayorDesk_Action(obj, activator)
  local galia = CH("Galia")

  COMMON.CharRealize("Galia")
  GROUND:CharTurnToCharAnimated(galia, activator, 2)
  GROUND:MoveToPosition(galia, activator.Position.X, galia.Position.Y, false, 1)
  GROUND:CharAnimateTurnTo(galia, Dir8.Down, 2)

  if SV.guild.day <= 1 then
    COMMON.SetCharAndEmotion(galia, "Normal")
    UI:WaitShowDialogue("Greetings, child.[pause=35] If you are looking for the mayor, he is out for the week, I believe.")

    COMMON.SetCharAndEmotion(activator, "Normal")
    UI:WaitShowDialogue("I'm actually just looking for apples.[pause=30] This building looked important enough.")

    COMMON.SetCharAndEmotion(galia, "Worried")
    UI:WaitShowDialogue("Ah, yes,[pause=30] I can't do that for you. That is the mayor's job and[pause=20] he isn't present.")

    COMMON.SetCharAndEmotion(galia, "Happy")
    UI:WaitShowDialogue("Apologies for the inconvenience.")
  end

  GROUND:MoveToMarker(galia, MRKR("g1"), false, 1)
  GROUND:CharAnimateTurnTo(galia, Dir8.Down, 2)
end

function AppleMayor.MayorExit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTownMayor", "Enter")
end

function AppleMayor.MayorBack_Touch(obj, activator)
  GAME:FadeOut(false, 25)
  if SV.guild.day <= 1 then
    AppleBoss.Roomy()
  else
    GAME:EnterGroundMap("MayorRoom", "Enter")
  end
end

function AppleMayor.Whisp_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("[color=#63666A]P-please... stay q-quiet in the... l-library...")
end
return AppleMayor

