--[[
    init.lua
    Created: 09/20/2025 23:00:08
    Description: Autogenerated script file for the map AppleTownMayor.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local AppleTownMayor = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTownMayor.Init(map)
--Engine callback function
function AppleTownMayor.Init(map)


end

---AppleTownMayor.Enter(map)
--Engine callback function
function AppleTownMayor.Enter(map)

  GAME:FadeIn(20)

end

---AppleTownMayor.Exit(map)
--Engine callback function
function AppleTownMayor.Exit(map)


end

---AppleTownMayor.Update(map)
--Engine callback function
function AppleTownMayor.Update(map)
  Partner()
end

---AppleTownMayor.GameSave(map)
--Engine callback function
function AppleTownMayor.GameSave(map)


end

---AppleTownMayor.GameLoad(map)
--Engine callback function
function AppleTownMayor.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function AppleTownMayor.MayorEnter_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleMayor", "Enter")
end

function AppleTownMayor.AppleTownEntrance_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTown", "Enter2")
end

return AppleTownMayor

