--[[
    init.lua
    Created: 09/06/2024 14:01:43
    Description: Autogenerated script file for the map tarro_town.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local tarro_town = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---tarro_town.Init(zone)
--Engine callback function
function tarro_town.Init(zone)


end

---tarro_town.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function tarro_town.EnterSegment(zone, rescuing, segmentID, mapID)


end

---tarro_town.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function tarro_town.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---tarro_town.Rescued(zone, name, mail)
--Engine callback function
function tarro_town.Rescued(zone, name, mail)


end

return tarro_town

