--[[
    init.lua
    Created: 09/20/2025 23:00:08
    Description: Autogenerated script file for the map AppleTownMayor_pt2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local AppleTownMayor_pt2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleTownMayor_pt2.Init(map)
--Engine callback function
function AppleTownMayor_pt2.Init(map)
  COMMON.RespawnAllies()
  GROUND:TeleportTo(CH("Teammate1"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  GROUND:TeleportTo(CH("Teammate2"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
end

---AppleTownMayor_pt2.Enter(map)
--Engine callback function
function AppleTownMayor_pt2.Enter(map)

  GAME:FadeIn(20)

end

---AppleTownMayor_pt2.Exit(map)
--Engine callback function
function AppleTownMayor_pt2.Exit(map)


end

---AppleTownMayor_pt2.Update(map)
--Engine callback function
function AppleTownMayor_pt2.Update(map)
  Partner()
end

---AppleTownMayor_pt2.GameSave(map)
--Engine callback function
function AppleTownMayor_pt2.GameSave(map)


end

---AppleTownMayor_pt2.GameLoad(map)
--Engine callback function
function AppleTownMayor_pt2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function AppleTownMayor_pt2.MayorEnter_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleMayor_pt2", "Enter")
end

function AppleTownMayor_pt2.AppleTownEntrance_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("AppleTown_pt2", "Enter2")
end

function AppleTownMayor_pt2.Item_Touch(obj, activator)
  local item
  local choice = math.random(3)
  if choice == 3 then
    item = "berry_kebab"
  elseif choice then
    item = "berry_sitrus"
  else
    item = "packed_honey"
  end
  COMMON.GiftItem(activator, item)

  UI:SetSpeaker(activator)
  UI:SetSpeakerEmotion("Inspired")
  UI:WaitShowDialogue("(Woah, this is rare!)")
  GROUND:Hide("Item")
  Titem_found = true
end

--characters

function AppleTownMayor_pt2.Bullet_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("This strange investigation,[pause=45] it's so confusing.")
end

function AppleTownMayor_pt2.Tanker_Action(obj, activator)
  COMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("...elementary, my dear Bullet.[pause=25] It wouldn't be an investigation without a bit of mystery, hmhm?")
end

return AppleTownMayor_pt2

