--[[
    init.lua
    Created: 08/11/2024 14:35:15
    Description: Autogenerated script file for the map TarroTownHive.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local TarroTownHive = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownHive.Init(map)
--Engine callback function
function TarroTownHive.Init(map)
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true
  
end

---TarroTownHive.Enter(map)
--Engine callback function
function TarroTownHive.Enter(map)
  SleepingPuchi = false
  GAME:FadeIn(20)
end

---TarroTownHive.Exit(map)
--Engine callback function
function TarroTownHive.Exit(map)


end

---TarroTownHive.Update(map)
--Engine callback function
function TarroTownHive.Update(map)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  
  if GAME:IsKeyDown(66) then
    print("Partner")
    
  end
  if GAME:IsKeyDown(66) then
    COMMON.FaceEachother("PLAYER", "Teammate1")
    if SV.tarro_town.PieChapter == 6 then
      UI:SetSpeaker(azura)
      UI:SetSpeakerEmotion("Inspired")
      UI:WaitShowDialogue("Whoa,[pause=20] the hives are huge. I bet Ms. Mayor lives here.")

      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Makes you wonder what all the buzz is about.")

      UI:SetSpeaker(azura)
      UI:SetSpeakerEmotion("Stunned")
      UI:WaitShowDialogue("...you're starting to starting to sound like dad.")

      UI:SetSpeaker(maru)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue(".[pause=60].[pause=60][emote=Worried].[pause=60] ...[emote=Stunned]oh no.")
    else
      UI:SetSpeaker(azura)
      UI:SetSpeakerEmotion("Inspired")
      UI:WaitShowDialogue("The smell of honey is so good...!")
      UI:WaitShowDialogue("We should get some, please please please!")
      
      pouch_money = GAME:GetPlayerMoney()
      if pouch_money == 0 then
        UI:SetSpeaker(maru)
        UI:SetSpeakerEmotion("Stunned")
        UI:WaitShowDialogue("I would if we had anything to buy it with.")

        UI:SetSpeaker(azura)
        UI:SetSpeakerEmotion("Stunned")
        UI:WaitShowDialogue("Huh, where moneys go?")

        UI:SetSpeaker(maru)
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("Let's just come back later.")
      elseif pouch_money < 100 then
        UI:SetSpeaker(maru)
        UI:SetSpeakerEmotion("Sad")
        UI:WaitShowDialogue("I don't think we can afford it...")

        UI:SetSpeaker(azura)
        UI:SetSpeakerEmotion("Sad")
        UI:WaitShowDialogue("Awww...")
      elseif pouch_money < 200 then
        UI:SetSpeaker(maru)
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("We could buy one, but I think it'd be better to save up...")

        UI:SetSpeaker(azura)
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("Maybe... but the honey smells so good...")
      else
        UI:SetSpeaker(maru)
        UI:SetSpeakerEmotion("Happy")
        UI:WaitShowDialogue("We could buy one, sure")

        UI:SetSpeaker(azura)
        UI:SetSpeakerEmotion("Joyous")
        UI:WaitShowDialogue("Yippee!")
      end
    end
  end
end

---TarroTownHive.GameSave(map)
--Engine callback function
function TarroTownHive.GameSave(map)

end

---TarroTownHive.GameLoad(map)
--Engine callback function
function TarroTownHive.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function TarroTownHive.HoneyShop_Action(obj, activator)
  local cute = CH("Cute")
  local azura = CH('Teammate1')

  pouch_money = GAME:GetPlayerMoney()
  UI:SetSpeaker(cute)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Oh my goodness, hi hi hi!")
  local choices = {("Yes!"),
        ("No!")}
    UI:BeginChoiceMenu("What some honey?! Only 100 Poke!", choices, 1, 2)
    UI:WaitForChoice()
    result = UI:ChoiceResult()
    if result == 1 then
      if pouch_money < 100 then
        COMMON.CharSweatdrop("Cute")
        UI:SetSpeakerEmotion("Worried")
        UI:WaitShowDialogue("Sorry, I can't just give these on a discount.")
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue("Ms. Mayor refuses to let me give out our plentiful supply out of an event.")
      else
        SOUND:PlaySE("Battle/DUN_Money")
        GAME:RemoveFromPlayerMoney(100)
        GROUND:MoveToPosition(cute, 309, 181, false, 10)
        GAME:WaitFrames(70)
        SOUND:PlaySE("EVT_CH02_Item_Place")
        GROUND:MoveToPosition(cute, 323, 181, false, 10)
        GROUND:CharAnimateTurn(cute, Direction.DownRight, 2, true)
        GROUND:Unhide("PurchasedHoney")
        GAME:WaitFrames(20)
        GROUND:MoveToPosition(cute, 315, 175, false, 10)
        GROUND:CharAnimateTurn(cute, Direction.Down, 2, true)
        UI:SetSpeakerEmotion("Happy")
        GAME:GivePlayerItem("packed_honey")
        UI:WaitShowDialogue("There you go! Enjoy!")
        
        GROUND:Hide("PurchasedHoney")
        UI:SetSpeaker(azura)
        UI:SetSpeakerEmotion("Joyous")
        UI:WaitShowDialogue("Yeah! Honey!")
      end
    else
      UI:SetSpeaker(cute)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Oh? Not today? Oh well,[pause=35] s[emote=Happy]afe travels, then!")
    end
end

function TarroTownHive.TTSquare_HiveExit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  outside_enter = 3
  GAME:EnterGroundMap("TarroTownSquare", "TTSquare_WestEnter")
end

return TarroTownHive



