--[[
    init.lua
    Created: 10/16/2025 14:51:30
    Description: Autogenerated script file for the map DesertSW.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local DesertSW = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DesertSW.Init(map)
--Engine callback function
function DesertSW.Init(map)
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
  GROUND:TeleportTo(CH("Teammate1"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.DownRight, 0)
  GROUND:TeleportTo(CH("Teammate2"), CH("PLAYER").Position.X, CH("PLAYER").Position.Y, Dir8.UpRight, 0)
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
end

---DesertSW.Enter(map)
--Engine callback function
function DesertSW.Enter(map)

  GAME:FadeIn(20)

end

---DesertSW.Exit(map)
--Engine callback function
function DesertSW.Exit(map)


end

---DesertSW.Update(map)
--Engine callback function
function DesertSW.Update(map)
  Partner()
end

---DesertSW.GameSave(map)
--Engine callback function
function DesertSW.GameSave(map)


end

---DesertSW.GameLoad(map)
--Engine callback function
function DesertSW.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function DesertSW.cactus3_Action(obj, activator)
  if activator.Nickname == "Rexio" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(...cactus.)")
  elseif activator.Nickname == "Maru" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(How does a cactus even grow like that?)")
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(Three!)")
  end
end

function DesertSW.Skits_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Hey, uh, if you see a fancy Bellsprout around, please get in contact with the Sire team.")
end

-- Entrances

function DesertSW.N_Touch(obj, activator)
  GAME:EnterGroundMap("DesertNW", "SouthEnter")
end

function DesertSW.NE_Touch(obj, activator)
  GAME:EnterGroundMap("DesertN", "SouthWestEnter")
end

function DesertSW.E_Touch(obj, activator)
  GAME:EnterGroundMap("DesertS", "WestEnter")
end

return DesertSW

