--[[
    init.lua
    Created: 10/16/2025 14:51:30
    Description: Autogenerated script file for the map DesertSW.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local DesertSW = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DesertSW.Init(map)
--Engine callback function
function DesertSW.Init(map)
  EXPLCOMMON.AllyFollow(true, true)
end

---DesertSW.Enter(map)
--Engine callback function
function DesertSW.Enter(map)

  GAME:FadeIn(20)

end

---DesertSW.Exit(map)
--Engine callback function
function DesertSW.Exit(map)


end

---DesertSW.Update(map)
--Engine callback function
function DesertSW.Update(map)
  Partner()
end

---DesertSW.GameSave(map)
--Engine callback function
function DesertSW.GameSave(map)


end

---DesertSW.GameLoad(map)
--Engine callback function
function DesertSW.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function DesertSW.cactus3_Action(obj, activator)
  if activator.Nickname == "Rexio" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(...cactus.)")
  elseif activator.Nickname == "Maru" then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(How does a cactus even grow like that?)")
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(Three!)")
  end
end

function DesertSW.Skits_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Hey, uh, if you see a fancy Bellsprout around, please get in contact with the Sire team.")
end

-- Entrances

function DesertSW.N_Touch(obj, activator)
  GAME:EnterGroundMap("DesertNW", "SouthEnter")
end

function DesertSW.NE_Touch(obj, activator)
  GAME:EnterGroundMap("DesertN", "SouthWestEnter")
end

function DesertSW.E_Touch(obj, activator)
  GAME:EnterGroundMap("DesertS", "WestEnter")
end

return DesertSW

