--[[
    init.lua
    Created: 12/11/2025 11:20:44
    Description: Autogenerated script file for the map HertzRightT.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local HertzRightT = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzRightT.Init(map)
--Engine callback function
function HertzRightT.Init(map)
  EXPLCOMMON.ThreeTeam()
end

---HertzRightT.Enter(map)
--Engine callback function
function HertzRightT.Enter(map)

  GAME:FadeIn(20)

end

---HertzRightT.Exit(map)
--Engine callback function
function HertzRightT.Exit(map)


end

---HertzRightT.Update(map)
--Engine callback function
function HertzRightT.Update(map)

end

---HertzRightT.GameSave(map)
--Engine callback function
function HertzRightT.GameSave(map)


end

---HertzRightT.GameLoad(map)
--Engine callback function
function HertzRightT.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function HertzRightT.ExitE_Touch(obj, activator)
  --EXPLCOMMON.FadeEnterGround("HertzWest", "EnterE")
end

function HertzRightT.ExitW_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzCenter", "EnterE")
end

function HertzRightT.Kazen_Action(obj, activator)
  EXPLCOMMON.KazenService()
end

return HertzRightT

