--[[
    init.lua
    Created: 04/11/2025 09:13:22
    Description: Autogenerated script file for the map EntohTownNorth_ch2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.EntohTownNorth_ch2.cutscene'

-- Package name
local EntohTownNorth_ch2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownNorth_ch2.Init(map)
--Engine callback function
function EntohTownNorth_ch2.Init(map)
  if SV.entoh_town.firstfind == 0 or SV.entoh_town.firstfind == 2 then
    Entoh2.TheFlow()
    if SV.entoh_town.firstfind == 0 then
      SV.entoh_town.firstfind = 1
    end
  else
    GROUND:Hide("Chucky")

    COMMON.RespawnAllies()
    local partner = CH("Teammate1")
    if outside_enter == 1 then
      GROUND:TeleportTo(partner, 120, 460, Direction.Up, 0)
    end
    AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
    partner.CollisionDisabled = true
  end
  FlowRexTalk = 0
end

---EntohTownNorth_ch2.Enter(map)
--Engine callback function
function EntohTownNorth_ch2.Enter(map)

  GAME:FadeIn(20)

end

---EntohTownNorth_ch2.Exit(map)
--Engine callback function
function EntohTownNorth_ch2.Exit(map)


end

---EntohTownNorth_ch2.Update(map)
--Engine callback function
function EntohTownNorth_ch2.Update(map)
  Partner()
end

---EntohTownNorth_ch2.GameSave(map)
--Engine callback function
function EntohTownNorth_ch2.GameSave(map)


end

---EntohTownNorth_ch2.GameLoad(map)
--Engine callback function
function EntohTownNorth_ch2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function EntohTownNorth_ch2.Entoh_SouthNExit_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownCenter_ch2", "EnterMark_North")
end

function EntohTownNorth_ch2.Enoth_DeliveryNEnter_Touch(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("(Looks like Chucky got away somehow.)")
end

return EntohTownNorth_ch2

