--[[
    init.lua
    Created: 09/04/2024 21:36:42
    Description: Autogenerated script file for the map tarro_town_outside.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local tarro_town_outside = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---tarro_town_outside.Init(zone)
--Engine callback function
function tarro_town_outside.Init(zone)


end

---tarro_town_outside.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function tarro_town_outside.EnterSegment(zone, rescuing, segmentID, mapID)


end

---tarro_town_outside.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function tarro_town_outside.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---tarro_town_outside.Rescued(zone, name, mail)
--Engine callback function
function tarro_town_outside.Rescued(zone, name, mail)


end

return tarro_town_outside

