--[[
    init.lua
    Created: 03/17/2026 21:18:41
    Description: Autogenerated script file for the map HertzGuildOut.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local HertzGuildOut = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzGuildOut.Init(map)
--Engine callback function
function HertzGuildOut.Init(map)
  EXPLCOMMON.AllyFollow(true, false)
end

---HertzGuildOut.Enter(map)
--Engine callback function
function HertzGuildOut.Enter(map)

  GAME:FadeIn(20)

end

---HertzGuildOut.Exit(map)
--Engine callback function
function HertzGuildOut.Exit(map)


end

---HertzGuildOut.Update(map)
--Engine callback function
function HertzGuildOut.Update(map)
  Partner()
end

---HertzGuildOut.GameSave(map)
--Engine callback function
function HertzGuildOut.GameSave(map)


end

---HertzGuildOut.GameLoad(map)
--Engine callback function
function HertzGuildOut.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function HertzGuildOut.GuildEnter_Touch(obj, activator)
  
end

function HertzGuildOut.ExitS_Touch(obj, activator)
  EXPLCOMMON.FadeEnterGround("HertzUpT", "ExitN")
end

return HertzGuildOut

