--[[
    init.lua
    Created: 06/18/2025 19:16:47
    Description: Autogenerated script file for the map EntohTownEast.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.EntohTownEast.cutscene'

-- Package name
local EntohTownEast = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownEast.Init(map)
--Engine callback function
function EntohTownEast.Init(map)
  if SV.Story.flag == 0 or (SV.Story.flag[1] == "Flow" and SV.Story.flag[2] == 0) then
    East.TidyUp()
  else
   EXPLCOMMON.AllyFollow(true, true)
  end

  TidyRexTalk = 0
end

---EntohTownEast.Enter(map)
--Engine callback function
function EntohTownEast.Enter(map)
  if not Todungeonscene then
    GAME:FadeIn(20)
  else
    Todungeonscene = true
  end
end

---EntohTownEast.Exit(map)
--Engine callback function
function EntohTownEast.Exit(map)


end

---EntohTownEast.Update(map)
--Engine callback function
function EntohTownEast.Update(map)


end

---EntohTownEast.GameSave(map)
--Engine callback function
function EntohTownEast.GameSave(map)


end

---EntohTownEast.GameLoad(map)
--Engine callback function
function EntohTownEast.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function EntohTownEast.Entoh_CenterEnter_Touch(obj, activator)
  OutEnter = 1
  GAME:EnterGroundMap("EntohTownCenter_ch2", "EasternMarker")
end

return EntohTownEast

