--[[
    init.lua
    Created: 05/25/2026 22:21:38
    Description: Autogenerated script file for the map OsiasLake.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.OsiasLake.cutscene'

-- Package name
local OsiasLake = {}

-------------------------------
-- Map Callbacks
-------------------------------
---OsiasLake.Init(map)
--Engine callback function
function OsiasLake.Init(map)
  if SV.Story.sect == 3 then
    if SV.Story.flag == 0 then
      Osiases.GoingIn()
    else
      Osiases.Yikes()
    end
  else
    EXPLCOMMON.AllyFollow(true, false)
  end
end

---OsiasLake.Enter(map)
--Engine callback function
function OsiasLake.Enter(map)
  if Todungeonscene then
    Todungeonscene = false
  else
    GAME:FadeIn(20)
  end
end

---OsiasLake.Exit(map)
--Engine callback function
function OsiasLake.Exit(map)


end

---OsiasLake.Update(map)
--Engine callback function
function OsiasLake.Update(map)


end

---OsiasLake.GameSave(map)
--Engine callback function
function OsiasLake.GameSave(map)


end

---OsiasLake.GameLoad(map)
--Engine callback function
function OsiasLake.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return OsiasLake

