--[[
    init.lua
    Created: 06/29/2025 10:33:41
    Description: Autogenerated script file for the map ApartmentRooms.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.ApartmentRooms.cutscene'

-- Package name
local ApartmentRooms = {}

-------------------------------
-- Map Callbacks
-------------------------------
---ApartmentRooms.Init(map)
--Engine callback function
function ApartmentRooms.Init(map)

  GROUND:Hide("Tidy")
  if SV.entoh_town.HelperChapter == 0.1 then
    Apart.TidyIntro()
  end
  COMMON.CreateWalkArea("Mouse", CH("Mouse").Position.X, CH("Mouse").Position.Y, 75, 75)
end

---ApartmentRooms.Enter(map)
--Engine callback function
function ApartmentRooms.Enter(map)

  GAME:FadeIn(20)

end

---ApartmentRooms.Exit(map)
--Engine callback function
function ApartmentRooms.Exit(map)


end

---ApartmentRooms.Update(map)
--Engine callback function
function ApartmentRooms.Update(map)


end

---ApartmentRooms.GameSave(map)
--Engine callback function
function ApartmentRooms.GameSave(map)


end

---ApartmentRooms.GameLoad(map)
--Engine callback function
function ApartmentRooms.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- CharFunc
sand_talk = 0
rex_talk = 0
function ApartmentRooms.Mouse_Action(obj, activator)
  COMMON.FaceEachother(activator, obj)
  if SV.entoh_town.AdventureChapter > 1 then
    if sand_talk == 0 then
      UI:SetSpeaker(obj)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Tidy went with him.[pause=10] Not me.[pause=10] Seemed too suspicious.")
      sand_talk = 1
    else
      UI:SetSpeaker(obj)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Are you going anywhere?[pause=10] It doesn't really matter.[pause=10] But I'll miss ya.[pause=10] That's what I think.")

      UI:SetSpeaker(activator)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("It's not like I'm leaving.[pause=20] I'll be back, I'm sure.")

      UI:SetSpeaker(obj)
      UI:SetSpeakerEmotion("Determined")
      UI:WaitShowDialogue("The vibes say otherwise.")
    end
  else
    if sand_talk == 0 then
      UI:SetSpeaker(obj)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Hey, Rexio.[pause=10] Hope you're well.[pause=10]")
      UI:SetSpeakerEmotion("Worried")
      UI:WaitShowDialogue("Me?[pause=10] Maybe Tidy dislikes me.[pause=10] I'm not all clean.[pause=10]")
      UI:SetSpeakerEmotion("Sad")
      UI:WaitShowDialogue("But even then...[pause=10] I'm just more organized.[pause=10] Even more than Tidy.[pause=10]")
      UI:SetSpeakerEmotion("Pain")
      UI:WaitShowDialogue("I hope we're friends.[pause=10] She never shows it.[pause=10] Like, ever.[pause=10]")
      sand_talk = 1
    else
      UI:SetSpeaker(obj)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Guess it doesn't matter.[pause=10] I have other friends...[pause=10]")
    end
  end
end

-- EnterFunc

function ApartmentRooms.ApartExit_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownCenter", "HomeMarker")
end

function ApartmentRooms.RexioHome_Enter_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("RexioHome", "RexioHomeWay")
end

function ApartmentRooms.EmptyEnter_Touch(obj, activator)
  if rex_talk == 0 then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(Oh wooooooooow. Very interesting stuff in there.)")
    rex_talk = 1
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(If my sarcasm wasn't obvious...)")
  end
end

function ApartmentRooms.MouseTalk_Touch(obj, activator)
  local mouse = CH("Mouse")
  if SV.entoh_town.AdventureChapter == 1 then
    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Hey, Rexio.[pause=10] Got a sec?")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Wassup, Mousy boi?")

    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Ew.[pause=50] [emote=Pain]Don't call me that.[pause=10] Ever.")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Anyway, about your dad.[pause=10] He ran past.[pause=10] ...like really ran.")
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Passing on a message.[pause=10] \"Tell Rexio, \'go east\'\".")
    
    SV.entoh_town.AdventureChapter = 1.1
  end
end

function ApartmentRooms.Mampha_Action(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Rexio wehh!")

  UI:SetSpeaker(activator)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Mrs. Slash.")

  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Live well,[pause=30] and don't do anything dumb wehhhh.")
end

function ApartmentRooms.MouseHomeEnter_Touch(obj, activator)
  local mampha = CH("Mampha")
  COMMON.FaceEachother(mampha, activator)
  if SV.entoh_town.AdventureChapter < 5 then
    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Rexio!")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Mrs. Slash.")

    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("You know that you can't go in uninvited wehhhh.")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("[speed=0.1]...[speed=1.0]may I be invited?")

    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Haha![pause=50] N[emote=Normal]o.")
  else
    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Rexio wehh!")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Mrs. Slash.")

    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Don't you have somewhere to be wehhhh?")

    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("It might be lame, though...")

    UI:SetSpeaker(mampha)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("I'm sure your father will get you somewhere cool wehhhh.")
  end
end

function ApartmentRooms.PanchHome_Touch(obj, activator)
  UI:SetSpeaker(activator)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("...nah. His place looks absolutely trashed.")
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("...and bamboo'd.")
end

function ApartmentRooms.EncleenHouse_Touch(obj, activator)
  SOUND:FadeOutBGM(100)
  GAME:WaitFrames(100)
  COMMON.CharSweatdrop("PLAYER")
  UI:SetSpeaker(activator)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(...I feel like a grand presence of someone pristine is watching me!)")
  SOUND:PlayBGM("Base Town.ogg", true)
end

function ApartmentRooms.Upper_Floor_Touch(obj, activator)
  UI:SetSpeaker(activator)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("(A worker outside said the second floor was a WIP.)")
end

return ApartmentRooms

