--[[
    init.lua
    Created: 06/29/2025 10:33:41
    Description: Autogenerated script file for the map ApartmentRooms.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'explorers_of_friending.ground.ApartmentRooms.cutscene'

-- Package name
local ApartmentRooms = {}

-------------------------------
-- Map Callbacks
-------------------------------
---ApartmentRooms.Init(map)
--Engine callback function
function ApartmentRooms.Init(map)

  GROUND:Hide("Tidy")
  if SV.entoh_town.HelperChapter == 0.1 then
    Apart.TidyIntro()
  end
  COMMON.CreateWalkArea("Mouse", CH("Mouse").Position.X, CH("Mouse").Position.Y, 75, 75)
end

---ApartmentRooms.Enter(map)
--Engine callback function
function ApartmentRooms.Enter(map)

  GAME:FadeIn(20)

end

---ApartmentRooms.Exit(map)
--Engine callback function
function ApartmentRooms.Exit(map)


end

---ApartmentRooms.Update(map)
--Engine callback function
function ApartmentRooms.Update(map)


end

---ApartmentRooms.GameSave(map)
--Engine callback function
function ApartmentRooms.GameSave(map)


end

---ApartmentRooms.GameLoad(map)
--Engine callback function
function ApartmentRooms.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-- CharFunc
sand_talk = 0
rex_talk = 0
function ApartmentRooms.Mouse_Action(obj, activator)
  COMMON.FaceEachother("PLAYER", "Mouse")
  local mouse = CH("Mouse")

  if sand_talk == 0 then
    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Hey, Rexio.[pause=10] Hope you're well.[pause=10]")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Me?[pause=10] Maybe Tidy hates me.[pause=10] I'm not all clean.[pause=10]")
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("I'm not too clean.[pause=10] I'm just more organized.[pause=10] Even more than Tidy.[pause=10]")
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("I hope we're friends.[pause=10] She never shows it.[pause=10] Like, ever.[pause=10]")
    sand_talk = 1
  else
    UI:SetSpeaker(mouse)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Guess it doesn't matter.[pause=10] I have other friends...[pause=10]")
  end
  
end

-- EnterFunc

function ApartmentRooms.ApartExit_Touch(obj, activator)
  GAME:FadeOut(10)
  GAME:EnterGroundMap("EntohTownCenter", "HomeMarker")
end

function ApartmentRooms.RexioHome_Enter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("RexioHome", "RexioHomeWay")
end

function ApartmentRooms.EmptyEnter_Touch(obj, activator)
  local rexio = CH("PLAYER")

  if rex_talk == 0 then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("(Oh wooooooooow. Very interesting stuff in there.)")
    rex_talk = 1
  else
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("(If my sarcasm wasn't obvious...)")
  end
end

return ApartmentRooms

