--[[
    init.lua
    Created: 11/16/2025 20:04:57
    Description: Autogenerated script file for the map DeepApple.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.DeepApple.cutscene'

-- Package name
local DeepApple = {}

-------------------------------
-- Map Callbacks
-------------------------------
---DeepApple.Init(map)
--Engine callback function
function DeepApple.Init(map)
  print(map)
  if SV.Story.sect == 2 then
    Core.AppleOut()
    if CH("Teammate1") ~= nil then
      CH("Teammate1").CollisionDisabled = true
      CH("Teammate2").CollisionDisabled = true
      AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
      AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
    end
    GROUND:Unhide("Exit")
  elseif SV.Story.sect == 3 then
    Core.Oof()
    GROUND:Unhide("Exit")
  end
end

---DeepApple.Enter(map)
--Engine callback function
function DeepApple.Enter(map)

  GAME:FadeIn(20)

end

---DeepApple.Exit(map)
--Engine callback function
function DeepApple.Exit(map)


end

---DeepApple.Update(map)
--Engine callback function
function DeepApple.Update(map)
  Partner()

end

---DeepApple.GameSave(map)
--Engine callback function
function DeepApple.GameSave(map)


end

---DeepApple.GameLoad(map)
--Engine callback function
function DeepApple.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function DeepApple.Storage_Action(obj, activator)
  COMMON.ShowTeamStorageMenu()
end

function DeepApple.Exit_Touch(obj, activator)
  if SV.Story.sect == 2 then
    if SV.apple_town.teamed == true then
      EXPLCOMMON.FaceEachother(CH("PLAYER"), CH("Teammate2"))
      GAME:WaitFrames(45)
      EXPLCOMMON.SetCharAndEmotion(activator, "Stunned")
      UI:WaitShowDialogue("(Rexio's giving me the stare of his life,[pause=35] backing out isn't an option yet.)")
      GROUND:AnimateToPosition(activator, "Walk", Dir8.Up, activator.Position.X, activator.Position.Y - 24, 0.7, 0.5, 0)
    else
      EXPLCOMMON.SetCharAndEmotion(activator, "Determined")
      UI:WaitShowDialogue("(No, no...! I need to prove myself!)")
    end
  else
    GAME:EnterGroundMap("apple_forest", "AppleTown_pt2", "ExitN")
  end
end

function DeepApple.Enter_Touch(obj, activator)
  if DUNGEON:LastDungeonResult() ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    EXPLCOMMON.FaceEachother(CH("PLAYER"), CH("Teammate2"))
    GAME:WaitFrames(45)
    EXPLCOMMON.SetCharAndEmotion(CH("Teammate2"), "Normal")
    UI:WaitShowDialogue("Hey, we can try this dungeon again.")

    EXPLCOMMON.SetCharAndEmotion(CH("PLAYER"), "Stunned")
    UI:WaitShowTimedDialogue("Rexio, you got pretty beaten up before. And Azura...", 45)

    EXPLCOMMON.SetCharAndEmotion(CH("Teammate2"), "Stunned")
    UI:WaitShowDialogue("Nope, let's go!")
  end
  local dungeon_entrances = {"dense_apple"}
  local ground_entrances = {}
  COMMON.ShowDestinationMenu(dungeon_entrances, ground_entrances)
end

return DeepApple

