--[[
    init.lua
    Created: 03/31/2025 09:28:22
    Description: Autogenerated script file for the map EntohTownCenter_ch2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'
require 'explorers_of_friending.ground.EntohTownCenter_ch2.cutscene'

-- Package name
local EntohTownCenter_ch2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownCenter_ch2.Init(map)
--Engine callback function
function EntohTownCenter_ch2.Init(map)
  if SV.entoh_town.HelperChapter == 5 then
    Center.Feeling()
    SV.entoh_town.HelperChapter = 6
  elseif SV.entoh_town.HelperChapter == 8 then
    GAME:RemovePlayerTeam(1)
    GAME:RemovePlayerTeam(1)
    GAME:RemovePlayerTeam(1)
    GAME:RemovePlayerTeam(1)
    Center.AnotherFeeling()
  end

  COMMON.RespawnAllies()
  
  if SV.entoh_town.HelperChapter == 7 then
    local partner = CH('Teammate1')
    local partner2 = CH('Teammate2')
    GROUND:TeleportTo(partner, CH('PLAYER').Position.X, CH('PLAYER').Position.Y - 24, Direction.Left, 0)
    GROUND:TeleportTo(partner2, CH('PLAYER').Position.X, CH('PLAYER').Position.Y + 24, Direction.Left, 0)
    AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
    AI:SetCharacterAI(partner2, "origin.ai.ground_partner", CH('Teammate1'), partner2.Position)
    partner.CollisionDisabled = true
    partner2.CollisionDisabled = true
  else
    local partner = CH('Teammate1')
    AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
    partner.CollisionDisabled = true
  end
end

---EntohTownCenter_ch2.Enter(map)
--Engine callback function
function EntohTownCenter_ch2.Enter(map)
  GAME:FadeIn(20)
end

---EntohTownCenter_ch2.Exit(map)
--Engine callback function
function EntohTownCenter_ch2.Exit(map)


end

---EntohTownCenter_ch2.Update(map)
--Engine callback function
function EntohTownCenter_ch2.Update(map)

  Partner()
end

---EntohTownCenter_ch2.GameSave(map)
--Engine callback function
function EntohTownCenter_ch2.GameSave(map)


end

---EntohTownCenter_ch2.GameLoad(map)
--Engine callback function
function EntohTownCenter_ch2.GameLoad(map)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function EntohTownCenter_ch2.WaterHole_Action(obj, activator)
  local rexio = CH("PLAYER")
  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(...nope... nothing...)")
end

function EntohTownCenter_ch2.Apartments_Enter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("ApartmentRooms_ch2", "exit_3")
end

function EntohTownCenter_ch2.Entoh_EastEnter_Touch(obj, activator)
  if SV.entoh_town.HelperChapter >= 9 then
    local rexio = CH("PLAYER")
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(...not now...)")
  else
    OutEnter = 1
    GAME:FadeOut(false, 20)
    GAME:EnterGroundMap("EntohTownEast", "Entrance")
  end
end

function EntohTownCenter_ch2.Entoh_SouthEnter_Touch(obj, activator)
  if SV.entoh_town.HelperChapter >= 9 then
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(No one knew where dad was...)")
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("(Probably no point in going back.)")
  else
    UI:SetSpeaker(activator)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(I have this strange feeling that something's going on down there.)")
    UI:SetSpeakerEmotion("Worried")
    UI:ChoiceMenuYesNo("(Should I...?)", false)
    UI:WaitForChoice()
    local result = UI:ChoiceResult()
    if result then
      GAME:FadeOut(false, 20)
      GAME:EnterGroundMap("EntohTownSouth", "EnterMark_North")
    end
  end
end

function EntohTownCenter_ch2.Entoh_NorthEnter_Touch(obj, activator)
  if SV.entoh_town.HelperChapter >= 9 then
    local rexio = CH("PLAYER")
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("(...not now...)")
  else
    GAME:FadeOut(false, 10)
    GAME:EnterGroundMap("EntohTownNorth_ch2", "EnterMark_South")
  end
  
end

return EntohTownCenter_ch2

