--[[
    init.lua
    Created: 09/21/2025 23:31:45
    Description: Autogenerated script file for the map AppleMayor_pt2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local AppleMayor_pt2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleMayor_pt2.Init(map)
--Engine callback function
function AppleMayor_pt2.Init(map)
  COMMON.RespawnAllies()
  AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
  AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
  CH("Teammate1").CollisionDisabled = true
  CH("Teammate2").CollisionDisabled = true
end

---AppleMayor_pt2.Enter(map)
--Engine callback function
function AppleMayor_pt2.Enter(map)

  GAME:FadeIn(20)

end

---AppleMayor_pt2.Exit(map)
--Engine callback function
function AppleMayor_pt2.Exit(map)


end

---AppleMayor_pt2.Update(map)
--Engine callback function
function AppleMayor_pt2.Update(map)

end

---AppleMayor_pt2.GameSave(map)
--Engine callback function
function AppleMayor_pt2.GameSave(map)


end

---AppleMayor_pt2.GameLoad(map)
--Engine callback function
function AppleMayor_pt2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function AppleMayor_pt2.MayorExit_Touch(obj, activator)
  GAME:EnterGroundMap("AppleTownMayor_pt2", "Enter")
end

function AppleMayor_pt2.Counter_Action(obj, activator)
  UI:SetSpeaker(GAME:GetPlayerPartyMember(0))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Hello?[pause=35] Room service?")

  UI:SetSpeaker(GAME:GetPlayerPartyMember(2))
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("...what...?")
end

function AppleMayor_pt2.MayorBack_Touch(obj, activator)
  EXPLCOMMON.CharSweatdrop("Teammate2")

  UI:SetSpeaker(GAME:GetPlayerPartyMember(2))
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Bluetail, I promise you there aren't any apples in there.")
end

local cut
function AppleMayor_pt2.Cut_Touch(obj, activator)
  local maru = GAME:GetPlayerPartyMember(0)
  local azura = GAME:GetPlayerPartyMember(1)
  local rexio = GAME:GetPlayerPartyMember(2)
 
  if cut == nil then
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("...[pause=35]was that really it?")

   EXPLCOMMON.FaceEachother(azura, rexio)
   EXPLCOMMON.CharQuestion("Teammate1")
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("...huh?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Are we really just about to leave with[pause=30], no treasure or anything...?")

   EXPLCOMMON.FaceEachother(maru, rexio)
    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("What treasure would we find here?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Uh... well,[pause=35] maybe[emote=Worried] a golden apple?")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("I just thought we'd be doing more...")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Like epicly fighting weird goo monsters?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Yeah, just li-[pause=70][speed=0.1]...[pause=60][speed=1.0] s[emote=Angry]hut up!")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowTimedDialogue("...u-um...?", 70)

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Whatever... *grumble grumble*")
    cut = true
  end
end

return AppleMayor_pt2

