--[[
    init.lua
    Created: 09/21/2025 23:31:45
    Description: Autogenerated script file for the map AppleMayor_pt2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local AppleMayor_pt2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---AppleMayor_pt2.Init(map)
--Engine callback function
function AppleMayor_pt2.Init(map)
  if SV.guild.time >= 40 then
    COMMON.RespawnAllies()
    AI:SetCharacterAI(CH("Teammate1"), "origin.ai.ground_partner", CH('PLAYER'), CH("Teammate1").Position)
    AI:SetCharacterAI(CH("Teammate2"), "origin.ai.ground_partner", CH("Teammate1"), CH("Teammate2").Position)
  end
end

---AppleMayor_pt2.Enter(map)
--Engine callback function
function AppleMayor_pt2.Enter(map)

  GAME:FadeIn(20)

end

---AppleMayor_pt2.Exit(map)
--Engine callback function
function AppleMayor_pt2.Exit(map)


end

---AppleMayor_pt2.Update(map)
--Engine callback function
function AppleMayor_pt2.Update(map)


end

---AppleMayor_pt2.GameSave(map)
--Engine callback function
function AppleMayor_pt2.GameSave(map)


end

---AppleMayor_pt2.GameLoad(map)
--Engine callback function
function AppleMayor_pt2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function AppleMayor_pt2.MayorExit_Touch(obj, activator)
  GAME:EnterGroundMap("AppleTownMayor_pt2", "Enter")
end

return AppleMayor_pt2

