--[[
    init.lua
    Created: 01/03/2025 23:19:02
    Description: Autogenerated script file for the map SennaHome.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local SennaHome = {}

-------------------------------
-- Map Callbacks
-------------------------------
---SennaHome.Init(map)
--Engine callback function
function SennaHome.Init(map)
  MapStrings = STRINGS.MapStrings
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')  
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
  partner.CollisionDisabled = true
end

---SennaHome.Enter(map)
--Engine callback function
function SennaHome.Enter(map)

  GAME:FadeIn(20)

end

---SennaHome.Exit(map)
--Engine callback function
function SennaHome.Exit(map)


end

---SennaHome.Update(map)
--Engine callback function
function SennaHome.Update(map)


end

---SennaHome.GameSave(map)
--Engine callback function
function SennaHome.GameSave(map)


end

---SennaHome.GameLoad(map)
--Engine callback function
function SennaHome.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

local ktalk = 0

function SennaHome.Senna_Action(obj, activator)
  local maru = CH("PLAYER")
  local azura = CH('Teammate1')
  local senna = CH("Senna")
  local ziggy = CH("Ziggy")

  if ktalk == 0 then
    UI:SetSpeaker(senna)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("I don't know if my brain could handle it...")
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("You saw how I was in that dungeon.")

    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Pfffffft[pause=25], you'll be fiiiiiine!")

    UI:SetSpeaker(senna)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("Mmm,[pause=40] s[emote=Stunned]ome other time, m-maybe?")

    GAME:WaitFrames(10)
    COMMON.FaceEachother("Ziggy", "Teammate1")
    
    GAME:WaitFrames(10)
    COMMON.FaceEachother("Senna", "PLAYER")

    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("AZU!")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("ZIG!")

    UI:SetSpeaker(senna)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Hey, Maru. Azura. Been a while since you've visited.")
    UI:WaitShowDialogue("Ziggy and I were talking about more dungeons...")

    COMMON.FaceEachother("Ziggy", "Senna")

    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Yeah! Senna's got great at battling!")

    UI:SetSpeaker(maru)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("That is true.")

    UI:SetSpeaker(senna)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("I would love to, but I'm [emote=Worried]still worried I'd slip up...")
    ktalk = 1
  else
    COMMON.FaceEachother("Senna", "PLAYER")
    UI:SetSpeaker(senna)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("I'd be happy to go with you guys.")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("But me?[pause=20] Alone?[pause=32] N[emote=Normal]o way...")
  end
end

function SennaHome.Ziggy_Action(obj, activator)
  
  local azura = CH('Teammate1')
  local ziggy = CH("Ziggy")

  if ktalk == 0 then
    SennaHome.Senna_Action()
  elseif ktalk == 1 then
    COMMON.FaceEachother("Ziggy", "Teammate1")
    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Azu Azu Azu! Guess what!")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Uh-huh?")

    GAME:GivePlayerItem("food_apple")
    SOUND:PlayFanfare("Fanfare/Item")
    UI:ResetSpeaker()
    UI:WaitShowDialogue("Ziggy gives Azura an apple...?")

    COMMON.CharHop("Ziggy")
    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("Yippee!")

    COMMON.CharHop("Teammate1")
    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Joyous")
    UI:WaitShowDialogue("Yippee!")
    ktalk = 2
  else
    UI:SetSpeaker(ziggy)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Azu!")

    UI:SetSpeaker(azura)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Zig!")
  end
  
end

function SennaHome.Beel_Action(obj, activator)
  local beel = CH("Beel")

  UI:SetSpeaker(beel)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("I always thought that getting straight to the point was the way to go...")

  COMMON.FaceEachother("PLAYER", "Beel")
  UI:SetSpeaker(beel)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I was proven wrong by Furie.[pause=10] My life has never been the same after that...")

end

function SennaHome.WaterHole_Action(obj, activator)
  local maru = CH("PLAYER")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(This water hole is deeper than ours, and it looks like there's money at the bottom...)")
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("(There's probably a reason, but I kinda wanna swim in and get it.)")
end

function SennaHome.CookFire_Action(obj, activator)
  local maru = CH("PLAYER")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(I'm probably better off using the one at home for now...)")
end

function SennaHome.SennaBasement_Entrance_Touch(obj, activator)
  local beel = CH("Beel")
  
  COMMON.FaceEachother("Beel", "PLAYER")
  UI:SetSpeaker(beel)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Oi, Maru.[pause=10] That room's for family members only.")
end

function SennaHome.SennaHome_Exit_Touch(obj, activator)
  print("Exiting?")
  outside_enter = 3
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("TarroTownEast_ch3", "TTEast_SennaHomeEnter")
end

return SennaHome

