--[[
    init.lua
    Created: 08/11/2024 14:35:15
    Description: Autogenerated script file for the map TarroTownEast_ch2.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local TarroTownEast_ch2end = {}

-------------------------------
-- Map Callbacks
-------------------------------
---TarroTownEast_ch2.Init(map)
--Engine callback function
function TarroTownEast_ch2end.Init(map)
  TarroTownEast_ch2end.WentWhere()
end

---TarroTownEast_ch2.Enter(map)
--Engine callback function

function TarroTownEast_ch2end.WentWhere()
  local maru = CH("Maru")
  local azura = CH("Azura")
  local senna = CH('Senna')
  local ziggy = CH('Ziggy')
  local puchi = CH('Puchi')

  local arama = CH('Arama')
  local amazuru = CH("Amazuru")
  local furie = CH('Furie')
  local beel = CH('Beel')
  GAME:CutsceneMode(true)
  GAME:MoveCamera(375, 425, 0, false)

  UI:SetSpeakerReverse(false)
  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("[speed=0.6]You two went wheere?!")
  
  UI:SetSpeakerReverse(true)
  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("[speed=0.6]You two went w[emote=Angry]heeeere?!")
  GAME:FadeIn(35)

  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("I can't believe it...!")
  
  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowTimedDialogue("Exactly, Furie. What you two did was r-")

  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Wonderful!")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowTimedDialogue("Yes, exa-", 10)

  local coro1 = TASK:BranchCoroutine(function()
    GROUND:CharTurnToCharAnimated(arama, furie, 9)
    end)	
  local coro2 = TASK:BranchCoroutine(function() 
    UI:SetSpeaker(arama)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("[speed=2.0]What?")
    end)

  TASK:JoinCoroutines({coro1, coro2})

  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Inspired")
  UI:WaitShowDialogue("Our little Senna got over her fear!")

  UI:SetSpeaker(senna)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("It was nothing, mama.")
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Ziggy helped me get through it, really...")

  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Oh, Ziggy,[pause=30] probably running off again...")

  UI:SetSpeaker(ziggy)
  UI:SetSpeakerEmotion("Joyous")
  UI:WaitShowDialogue("What can I say?[pause=20] Adventures are fun!")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Wait wait wait, no no no no no no!")
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Furie,[pause=20] I know that you're glad for you kid,[pause=20] but you shouldn't let Ziggian keep running off like that!")

  GROUND:CharTurnToCharAnimated(arama, ziggy, 9)
  UI:SetSpeaker(ziggy)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Mrs. Bluetail, please[emote=Pain] don't call me that...")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What made you kids want to go in there anyway?!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("We heard a thing explode!")

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("It was all like,[pause=30] B[emote=Shouting]OOM!")

  UI:SetSpeaker(senna)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("We went in the [color=#01FE10]Big Tree[color] and th-there was a thing!")

  UI:SetSpeaker(azura)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("It was all like,[pause=30][emote=Dizzy] mlehhhhhhh!")

  UI:SetSpeaker(ziggy)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("And there were five more of them hurting the tree!")
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("We had to fight them!")

  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("T-[color=#01FE10]Tarro Tree[color]!")

  UI:SetSpeaker(beel)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Strange,[pause=20] I feel like I would've heard that explosion.")

  UI:SetSpeaker(ziggy)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("You, too, dad?!")

  UI:SetSpeaker(maru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(Why could no one else hear it...?)")

  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("You four have to warn us first, okay...!")

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Big adventures leveling up in the world.")

  COMMON.FaceEachother("Arama", "Furie")
  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Furie, you have to control your child!")

  GROUND:CharTurnToCharAnimated(amazuru, arama, 4)
  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("I see no need, Mrs. Arama. Our kids are clearly showing to be capable.")

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Yeah, all thanks to my training.")

  GROUND:CharTurnToCharAnimated(beel, arama, 4)
  UI:SetSpeaker(arama)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("Now's not the time honey! Our kids put themselves in danger!")

  UI:SetSpeaker(beel)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("With all due respect, Arama, you shouldn't underestimate them just because they're younger...")
  UI:WaitShowDialogue("Isn't that right, Amazuru.")

  GROUND:CharTurnToCharAnimated(amazuru, ziggy, 4)
  COMMON.CharSweatdrop("Amazuru")
  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Oh, geez,[pause=30] don't remind me...")

  UI:SetSpeaker(puchi)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("[speed=0.4]I'm... going home...")

  UI:ResetSpeaker()
  local coro01 = TASK:BranchCoroutine(function()
    GROUND:CharAnimateTurn(azura, Direction.Left, 5, false)
    GROUND:CharAnimateTurn(maru, Direction.Left, 4, false)
    GROUND:CharAnimateTurn(puchi, Direction.Left, 2, false)
    GROUND:CharAnimateTurn(senna, Direction.Left, 2, false)
    GROUND:CharAnimateTurn(ziggy, Direction.Left, 8, false)
    end)
  local coro02 = TASK:BranchCoroutine(function()
    GROUND:CharAnimateTurn(arama, Direction.Left, 5, false)
    GROUND:CharAnimateTurn(amazuru, Direction.Left, 5, false)
    GROUND:CharAnimateTurn(beel, Direction.Left, 6, false)
    GROUND:CharAnimateTurn(furie, Direction.Left, 5, false)
    end)
  local coro03 = TASK:BranchCoroutine(function() 
    UI:WaitShowDialogue("[speed=1.5]PUUUUUUUUCH[speed=0.7]IIIIIIIIIIIIIII!!")
    end)
  TASK:JoinCoroutines({coro01, coro02, coro03})
  UI:SetSpeaker(furie)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Oh dear...")

  UI:SetSpeaker(amazuru)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Wuh oh...")
  GAME:WaitFrames(85)
  local coro001 = TASK:BranchCoroutine(function()
    GAME:WaitFrames(15)
    UI:SetSpeaker(puchi)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("I'm just...[pause=75] so tired...")

    GAME:FadeOut(false, 40)
    end)
  local coro002 = TASK:BranchCoroutine(function()
    COMMON.CharSweatdrop("Puchi")
    GAME:WaitFrames(40)
    GROUND:MoveToPosition(puchi, 100, 420, false, 0.7)
    end)
  TASK:JoinCoroutines({coro001, coro002})

  GAME:CutsceneMode(false)
  GAME:EnterGroundMap("MaruHome", "MaruHome_MainEnter")
end

function TarroTownEast_ch2end.Enter(map)
  
  GAME:FadeIn(20)
  
end

---TarroTownEast_ch2.Exit(map)
--Engine callback function
function TarroTownEast_ch2end.Exit(map)


end

---TarroTownEast_ch2.Update(map)
--Engine callback function
function TarroTownEast_ch2end.Update(map)

end

---TarroTownEast_ch2.GameSave(map)
--Engine callback function
function TarroTownEast_ch2end.GameSave(map)

end

---TarroTownEast_ch2.GameLoad(map)
--Engine callback function
function TarroTownEast_ch2end.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

return TarroTownEast_ch2end



