--[[
    init.lua
    Created: 07/14/2025 21:58:43
    Description: Autogenerated script file for the map swamp_town.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local swamp_town = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---swamp_town.Init(zone)
--Engine callback function
function swamp_town.Init(zone)


end

---swamp_town.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function swamp_town.EnterSegment(zone, rescuing, segmentID, mapID)


end

---swamp_town.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function swamp_town.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---swamp_town.Rescued(zone, name, mail)
--Engine callback function
function swamp_town.Rescued(zone, name, mail)


end

return swamp_town

