--[[
    init.lua
    Created: 04/18/2025 20:48:29
    Description: Autogenerated script file for the map EntohTownDelivery.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local EntohTownDelivery = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownDelivery.Init(map)
--Engine callback function
function EntohTownDelivery.Init(map)
  local down = CH("Down")
  GROUND:CharSetAnim(down, "Sleep", true)
end

---EntohTownDelivery.Enter(map)
--Engine callback function
function EntohTownDelivery.Enter(map)

  GAME:FadeIn(20)

end

---EntohTownDelivery.Exit(map)
--Engine callback function
function EntohTownDelivery.Exit(map)


end

---EntohTownDelivery.Update(map)
--Engine callback function
function EntohTownDelivery.Update(map)


end

---EntohTownDelivery.GameSave(map)
--Engine callback function
function EntohTownDelivery.GameSave(map)


end

---EntohTownDelivery.GameLoad(map)
--Engine callback function
function EntohTownDelivery.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function EntohTownDelivery.Entoh_DeliSouthEnter_Touch(obj, activator)
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownNorth", "EnterMark_NNorth")
end

return EntohTownDelivery

