--[[
    init.lua
    Created: 03/06/2025 22:41:41
    Description: Autogenerated script file for the map the_field.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local the_field = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---the_field.Init(zone)
--Engine callback function
function the_field.Init(zone)


end

---the_field.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function the_field.EnterSegment(zone, rescuing, segmentID, mapID)


end

---the_field.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function the_field.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---the_field.Rescued(zone, name, mail)
--Engine callback function
function the_field.Rescued(zone, name, mail)


end

return the_field

