--[[
    init.lua
    Created: 12/21/2025 10:26:28
    Description: Autogenerated script file for the map HertzShopsA.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local HertzShopsA = {}

-------------------------------
-- Map Callbacks
-------------------------------
---HertzShopsA.Init(map)
--Engine callback function
function HertzShopsA.Init(map)
 EXPLCOMMON.AllyFollow(true, false)
  if CacHidden == true then
    GROUND:Hide("Cacnea")
  end
end

---HertzShopsA.Enter(map)
--Engine callback function
function HertzShopsA.Enter(map)

  GAME:FadeIn(20)

end

---HertzShopsA.Exit(map)
--Engine callback function
function HertzShopsA.Exit(map)


end

---HertzShopsA.Update(map)
--Engine callback function
function HertzShopsA.Update(map)
  Partner()
end

---HertzShopsA.GameSave(map)
--Engine callback function
function HertzShopsA.GameSave(map)


end

---HertzShopsA.GameLoad(map)
--Engine callback function
function HertzShopsA.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function HertzShopsA.TrinketSeller_Action(obj, activator)
  local pouch_money = GAME:GetPlayerMoney()

  if trinktalk == nil then
   EXPLCOMMON.SetCharAndEmotion(obj, "Normal")
    UI:WaitShowDialogue("I sell trinkets, you want a trinket?[pause=40][emote=Happy] I gots trinkets there and here and here and there.")

    local maru = CH("PLAYER")
    local azura = CH("Teammate1")
    local rexio = CH("Teammate2")

   EXPLCOMMON.SetCharAndEmotion(azura, "Inspired")
    UI:WaitShowDialogue("Ooh! I want one!")

   EXPLCOMMON.SetCharAndEmotion(maru, "Normal")
    UI:WaitShowDialogue("Is a pass a trinket?")

   EXPLCOMMON.SetCharAndEmotion(obj, "Worried")
    UI:WaitShowDialogue("Well, probably not, I think[pause=45],[emote=Normal] but I do sell them.")

   EXPLCOMMON.SetCharAndEmotion(rexio, "Normal")
    UI:WaitShowDialogue("Give it.")

   EXPLCOMMON.SetCharAndEmotion(obj, "Sigh")
    UI:WaitShowDialogue("This isn't a charity, kid. You gotta pay up, 100 of those cool coins.")

    if pouch_money < 100 then
     EXPLCOMMON.FaceEachother(maru, rexio)

     EXPLCOMMON.SetCharAndEmotion(rexio, "Worried")
      UI:WaitShowDialogue("This is so inconvenient.[pause=0] And it's boring, too.")

     EXPLCOMMON.SetCharAndEmotion(maru, "Normal")
      UI:WaitShowDialogue("There is a storage thing outside, could get money from that.")

     EXPLCOMMON.SetCharAndEmotion(rexio, "Stunned")
      UI:WaitShowDialogue("And what if that's empty?")

     EXPLCOMMON.SetCharAndEmotion(azura, "Happy")
      UI:WaitShowDialogue("Let's ask Mr. Smear!")
      trinktalk = 1
    end
  end

  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Happy")
  local choices = {
    ("Yes!"),
    ("No!")
  }
  UI:BeginChoiceMenu("So how 'bout it?", choices, 1, 2)
  UI:WaitForChoice()
  result = UI:ChoiceResult()
  if result == 1 then
    if pouch_money < 100 then
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("...funny. Right, that's not the number, kid.[pause=40] I said 100.")
    else
      SOUND:PlaySE("Battle/DUN_Money")
      GAME:RemoveFromPlayerMoney(100)
      GAME:WaitFrames(20)

      SV.hertz_town.passcount = SV.hertz_town.passcount + 1

      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Nice doin' business. You've got " .. SV.hertz_town.passcount .. " passes, yeah?")
    end
  else
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Hm.")
  end
end

function HertzShopsA.BerrySeller_Action(obj, activator)
 EXPLCOMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("Sorry, this shop is closed.[pause=45] [color=#EFBF04]It's uh... missing something right now.[color]")
end

function HertzShopsA.Meteor_Action(obj, activator)
 EXPLCOMMON.SetCharAndEmotion(obj, "Normal")
  UI:WaitShowDialogue("I feel like I just fell out of the sky.[pause=45] What town is this again?")
end

function HertzShopsA.Chucky_Action(obj, activator)
  local rexio = CH("Teammate2")

  if convo == nil then
    HertzShopsA.Kyuki_Action(CH("Kyuki"), activator)
  else
   EXPLCOMMON.SetCharAndEmotion(obj, "Happy")
    UI:WaitShowDialogue("I'm Chucky, by the way.")

   EXPLCOMMON.SetCharAndEmotion(activator, "Sad")
  UI:WaitShowDialogue("Nice to meet you, too.")
  end
end

function HertzShopsA.Kyuki_Action(obj, activator)
  local chuck = CH("Chucky")
  local azura = CH("Teammate1")
  local rexio = CH("Teammate2")
 EXPLCOMMON.SetCharAndEmotion(obj, "Sad")
  UI:WaitShowDialogue("B-but... but what if I'm too spooky...")

 EXPLCOMMON.SetCharAndEmotion(chuck, "Worried")
  UI:WaitShowDialogue("Spooky?[pause=45] Your disguise isn't really spooky,[pause=45] could use some work actually...")

 EXPLCOMMON.FaceEachother(obj, activator)
 EXPLCOMMON.FaceEachother(chuck, activator)
 EXPLCOMMON.SetCharAndEmotion(chuck, "Happy")
  UI:WaitShowDialogue("Look, there's some new people, talk to them!")

 EXPLCOMMON.SetCharAndEmotion(activator, "Happy")
  UI:WaitShowDialogue("Hello.")

 EXPLCOMMON.SetCharAndEmotion(obj, "Sad")
  UI:WaitShowDialogue("...u-um... hello. I'm Kyuki... nice to, uh...")

 EXPLCOMMON.SetCharAndEmotion(rexio, "Worried")
  UI:WaitShowDialogue("That's a boring way to start anything...")

 EXPLCOMMON.CharSweating("Kyuki")
 EXPLCOMMON.SetCharAndEmotion(obj, "Worried")
  UI:WaitShowDialogue("I'm... I'm sorry.")

 EXPLCOMMON.SetCharAndEmotion(azura, "Happy")
  UI:WaitShowDialogue("I think we can be friends.")

 EXPLCOMMON.SetCharAndEmotion(obj, "Inspired")
  UI:WaitShowDialogue("R-really?!")

 EXPLCOMMON.SetCharAndEmotion(activator, "Happy")
  UI:WaitShowDialogue("I also think we can be friends.")

  GAME:WaitFrames(90)
  GROUND:CharTurnToCharAnimated(activator, rexio, 4)
  GROUND:CharTurnToCharAnimated(azura, rexio, 4)
  GROUND:CharTurnToCharAnimated(chuck, rexio, 2)
  GROUND:CharTurnToCharAnimated(obj, rexio, 4)

 EXPLCOMMON.CharQuestion("Rexio")
 EXPLCOMMON.SetCharAndEmotion(rexio, "Worried")
  UI:WaitShowDialogue("...oh, uh,[pause=75] work [emote=Normal]on your intro first and then maybe probably maybe we can talk.")
end

function HertzShopsA.Cacnea_Action(obj, activator)
  local pouch_money = GAME:GetPlayerMoney()

 EXPLCOMMON.FaceEachother(obj, activator)
  UI:SetSpeaker(obj)
  UI:SetSpeakerEmotion("Happy")
  local choices = {
    ("Yes!"),
    ("No!")
  }
  UI:BeginChoiceMenu("Hey![pause=40] Gimme 100 Poke!", choices, 1, 2)
  UI:WaitForChoice()
  result = UI:ChoiceResult()
  if result == 1 then
    if pouch_money < 100 then
      UI:SetSpeakerEmotion("Angry")
      UI:WaitShowDialogue("Are you trying to con me?! That's not 100!")
    else
      SOUND:PlaySE("Battle/DUN_Money")
      GAME:RemoveFromPlayerMoney(100)
      GAME:WaitFrames(20)

      UI:SetSpeakerEmotion("Joyous")
      UI:WaitShowTimedDialogue("SUCKER!", 45)
      obj.CollisionDisabled = true
      GROUND:MoveToMarker(obj, MRKR("exit1"), false, 6)
      GROUND:MoveToMarker(obj, MRKR("exit2"), false, 6)
      GROUND:Hide("Cacnea")
      CacHidden = true
    end
  else
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("...coward.")
  end
end

function HertzShopsA.Exit_Touch(obj, activator)
 EXPLCOMMON.FadeEnterGround("HertzEntrance", "ShopOut")
end

return HertzShopsA

