--[[
    init.lua
    Created: 03/31/2025 09:28:22
    Description: Autogenerated script file for the map EntohTownCenter.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local EntohTownCenter = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownCenter.Init(map)
--Engine callback function
local flow_talk = 0
function EntohTownCenter.Init(map)

  COMMON.CreateWalkArea("Tidy", 200, 300, 48, 48)
  GROUND:CharSetAnim(CH("Flow"), "Sleep", true)
  if flow_talk == 1 then
    GROUND:CharSetAnim(CH("Flow"), "Idle", true)
  end
  if SV.entoh_town.AdventureChapter > 0 then
    GROUND:Hide("Tidy")
    GROUND:Hide("Flow")
    GROUND:Hide("Wurp")
    GROUND:Hide("Snow")
    GROUND:TeleportTo(CH("Worker"), 576, 176, Dir8.Down, 0)
    GROUND:Unhide("Sign")
  end
end

---EntohTownCenter.Enter(map)
--Engine callback function
function EntohTownCenter.Enter(map)

  GAME:FadeIn(20)

end

---EntohTownCenter.Exit(map)
--Engine callback function
function EntohTownCenter.Exit(map)


end

---EntohTownCenter.Update(map)
--Engine callback function
function EntohTownCenter.Update(map)


end

---EntohTownCenter.GameSave(map)
--Engine callback function
function EntohTownCenter.GameSave(map)


end

---EntohTownCenter.GameLoad(map)
--Engine callback function
function EntohTownCenter.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
local bug_talk = 0


function EntohTownCenter.Wurp_Action(obj, activator)
  local wurp = CH("Wurp")
  local dewey = CH("Dewey")
  local pari = CH("Pari")
  local snow = CH("Snow")
  local rexio = CH("PLAYER")
  UI:SetSpeakerLoc(256, 124)
  if bug_talk == 0 then
    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("By the powa of the Buggy Squad!")
    
    UI:SetSpeaker(dewey)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Uh-huh?")

    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("We will conquer da world, and then captuwe everyone's hearts!")
    
    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Oui, a world coup!")

    GROUND:CharTurnToCharAnimated(snow, rexio, 4)
    UI:SetSpeaker(snow)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("H-hey... it's Rexio...")

    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowTimedDialogue("Wexio?!", 30)
    
    GROUND:CharTurnToCharAnimated(dewey, rexio, 4)
    GROUND:CharTurnToCharAnimated(pari, rexio, 4)
    COMMON.FaceEachother("Wurp", "PLAYER")
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("What awe youuuuuuuuu doing here?")

    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowTimedDialogue("Yeah, Wexio-")
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowTimedDialogue("Er,[pause=30] I mean...", 15)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("[speed=10]Yeah, Rexio![speed=1.0] What are youuuuuu doing here?")

    if SV.entoh_town.HelperChapter < 3 then
      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Doin' chooooooores.")

      UI:SetSpeaker(wurp)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Ha![pause=25] Y[emote=Determined]ou'we doing da mowtals work.")
      UI:SetSpeakerEmotion("Determined")
      UI:WaitShowDialogue("The Buggy Wegion would neva fall so low...")

      GROUND:CharTurnToCharAnimated(dewey, wurp, 4)
      UI:SetSpeaker(dewey)
      UI:SetSpeakerEmotion("Stunned")
      UI:WaitShowDialogue("Aren't you supposed to be getting leaves for your mom?")

      GROUND:CharTurnToCharAnimated(wurp, dewey, 4)
      UI:SetSpeaker(wurp)
      UI:SetSpeakerEmotion("Angry")
      UI:WaitShowDialogue("Iwewevant!")

      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Ha!")
    else
      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Nothin'.")

      UI:SetSpeaker(wurp)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Ha![pause=25] Y[emote=Determined]ou'we wack of activity is exactly what we need!")

      UI:SetSpeaker(rexio)
      UI:SetSpeakerEmotion("Normal")
      UI:WaitShowDialogue("Oh yeah? What are you doing?")

      GROUND:CharTurnToCharAnimated(dewey, wurp, 4)
      GROUND:CharTurnToCharAnimated(pari, wurp, 4)
      GROUND:CharTurnToCharAnimated(snow, wurp, 4)
      GAME:WaitFrames(40)
      COMMON.CharSweatdrop("Wurp")
      UI:SetSpeaker(wurp)
      UI:SetSpeakerEmotion("Stunned")
      UI:WaitShowDialogue("W-we'ww, uh... caww it a stawemate fow now...")
    end
    UI:ResetSpeaker()
    bug_talk = 1
  else
    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Just you wait, bugs will be the best type eveh!")
  end
end

function EntohTownCenter.Dewey_Action(obj, activator)
  local dewey = CH("Dewey")
  local rexio = CH("PLAYER")
  if SV.entoh_town.AdventureChapter > 0 then
    COMMON.FaceEachother("Dewey", "PLAYER")
    UI:SetSpeaker(dewey)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Hey, Rexio.[pause=20] When you see Wurp, let him know that he still owes me, like, 50 Poke.")
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("He got saved by your dad whisking him away...")
  else
    if bug_talk == 0 then
      EntohTownCenter.Wurp_Action()
    else
      GROUND:CharTurnToCharAnimated(dewey, rexio, 4)
      UI:SetSpeaker(dewey)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Nice seeing you, Rexio.")
    end
  end
end

function EntohTownCenter.Snow_Action(obj, activator)
  local wurp = CH("Wurp")
  local snow = CH("Snow")
  local rexio = CH("PLAYER")
  if bug_talk == 0 then
    EntohTownCenter.Wurp_Action()
  else
    GROUND:CharTurnToCharAnimated(snow, rexio, 4)
    UI:SetSpeaker(snow)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("D-don't mind him, Rexio.")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("E-ever since he beat some... goopy thing in a dungeon, he's been...")
    GROUND:CharTurnToCharAnimated(snow, wurp, 4)
    UI:WaitShowDialogue("...acting strange.")
  end
end

function EntohTownCenter.Pari_Action(obj, activator)
  local pari = CH("Pari")
  local rexio = CH("PLAYER")
  if SV.entoh_town.AdventureChapter > 0 then
    COMMON.FaceEachother("Pari", "PLAYER")
    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Monsieur Rexi, to where is Wurpy going without taking moui!")
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("How are we to become leader mondial without chef d'équipe!")

  else
    if bug_talk == 0 then
      EntohTownCenter.Wurp_Action()
    else
      GROUND:CharTurnToCharAnimated(pari, rexio, 4)
      UI:SetSpeaker(pari)
      UI:SetSpeakerEmotion("Happy")
      UI:WaitShowDialogue("Do not get in our way, Monsieur Rexi. Ze world will be ours!")
    end
  end
end

function EntohTownCenter.Entoh_NorthEnter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownNorth", "EnterMark_South")
end

function EntohTownCenter.WaterHole_Action(obj, activator)
  local rexio = CH("PLAYER")
  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(It's weird...)")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(Every time I look at this water hole, I want to say something funny about it.)")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(But I just can't come up with anything...)")
end

function EntohTownCenter.Gran_Action(obj, activator)
  local gran = CH("Gran")
  UI:SetSpeaker(gran)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("[speed=0.6]Ahh, a spry young fella. I remember when I was your age...")
  UI:WaitShowDialogue("[speed=0.6]This place was full of mountains and rocks. [pause=75]F[emote=Worried]rankly dangerous to walk on for a while...")
end

function EntohTownCenter.Tidy_Action(obj, activator)
  local tidy = CH("Tidy")
  UI:SetSpeaker(tidy)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Stay clean, Rexxy!")
end

function EntohTownCenter.Apartments_Enter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("ApartmentRooms", "exit_3")
end

function EntohTownCenter.Entoh_EastEnter_Touch(obj, activator)
  local timb = CH("Worker")
  if SV.entoh_town.AdventureChapter > 0 then
    GAME:FadeOut(false, 20)
    GAME:EnterGroundMap("EntohTownEast_ch2", "Entrance_2")
  else
    UI:SetSpeaker(timb)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Services being done! You cannot pass through!")
  end
  
end

function EntohTownCenter.Entoh_SouthEnter_Touch(obj, activator)
  local timb = CH("Worker2")
  UI:SetSpeaker(timb)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Services being done! You cannot pass through!")
end

function EntohTownCenter.Flow_Action(obj, activator)
  local flow = CH("Flow")
  local rexio = CH("PLAYER")
  
  if flow_talk == 0 then
    UI:SetSpeaker(flow)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue("[speed=0.6]So light...[pause=30] so little...[pause=30] flow with the air like the flowers do...")
    
    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("...")

    UI:SetSpeaker(flow)
    UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowTimedDialogue("...[pause=65][speed=0.6] ...[pause=65] ...", 70)

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowTimedDialogue("Meep.", 15)
    
    COMMON.FaceEachother("Flow", "PLAYER")
    GROUND:CharSetAnim(CH("Flow"), "Charge", true)
    UI:SetSpeaker(flow)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Rexio! Stop ruining my concentration!")
    flow_talk = 1
    GROUND:CharSetAnim(CH("Flow"), "Idle", true)
  else
    COMMON.FaceEachother("Flow", "PLAYER")
    UI:SetSpeaker(flow)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Now I have to start all over...")
  end
  
end

function EntohTownCenter.Sign_Action(obj, activator)
  if sign_tutorial ~= 1 then
    UI:SetAutoFinish(true)
    UI:WaitShowDialogue("You can get dungeon points by doing certain things in a certain group of dungeons.")
    UI:WaitShowDialogue("Some dungeons, including this one, will only require completion. Other dungeons may require certain items to be turned in, or Pokemon to find.")
    UI:WaitShowDialogue("Getting enough dungeon experience will unlock things that will help you on your future journeys, so be sure to complete as many of these as you can.")
    sign_tutorial = 1
  end

  UI:SetAutoFinish(false)
  print(SV.entoh_thicket.dungpoints)
  print(SV.dreaded_depths.dungpoints)
  print(GAME:DungeonUnlocked("entoh_thicket"))
  print(GAME:DungeonUnlocked("dreaded_depths"))

  entoh_dungeonpoints = SV.dreaded_depths.dungpoints + SV.entoh_thicket.dungpoints
  if SV.deep_tarro_forest.dungpoints > 0 and SV.tarro_tree_hollows.dungpoints > 0 then
    UI:WaitShowDialogue("You currently have " ..tarro_dungeonpoints.. " dungeon points with the Tarro dungeons.")
    --set up some sort of shop behind Worker_1.
  else
    UI:WaitShowDialogue("You haven't explored all of the dungeons needed for this group.")
    UI:WaitShowDialogue("Recheck the sign after you find all of the Entoh dungeons:")
    if SV.dreaded_depths.dungpoints == 0 then
      if GAME:DungeonUnlocked("dreaded_depths") == false then
        UI:WaitShowDialogue("An undiscovered dungeon still needs to be explored.")
      else
        UI:WaitShowDialogue("The Dreaded Depths still needs to be explored.")
      end
    end
    UI:WaitShowDialogue("You currently have " ..tarro_dungeonpoints.. " dungeon points with the Tarro dungeons.")
  end
end

function EntohTownCenter.Worker_Action(obj, activator)
  local timba = CH("Worker")

  if SV.entoh_town.AdventureChapter > 0 then
    UI:SetSpeaker(timba)
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Thank goodness work on the East is over...")
  end
end

return EntohTownCenter

