--[[
    init.lua
    Created: 03/31/2025 09:28:22
    Description: Autogenerated script file for the map EntohTownCenter.
]]--
-- Commonly included lua functions and data
require 'explorers_of_friending.common'

-- Package name
local EntohTownCenter = {}

-------------------------------
-- Map Callbacks
-------------------------------
---EntohTownCenter.Init(map)
--Engine callback function
function EntohTownCenter.Init(map)

  COMMON.CreateWalkArea("Tidy", 200, 300, 48, 48)
end

---EntohTownCenter.Enter(map)
--Engine callback function
function EntohTownCenter.Enter(map)

  GAME:FadeIn(20)

end

---EntohTownCenter.Exit(map)
--Engine callback function
function EntohTownCenter.Exit(map)


end

---EntohTownCenter.Update(map)
--Engine callback function
function EntohTownCenter.Update(map)


end

---EntohTownCenter.GameSave(map)
--Engine callback function
function EntohTownCenter.GameSave(map)


end

---EntohTownCenter.GameLoad(map)
--Engine callback function
function EntohTownCenter.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
local bug_talk = 0
local wurp = CH("Wurp")
local dewey = CH("Dewey")
local pari = CH("Pari")
local snow = CH("Snow")
local rexio = CH("PLAYER")
function EntohTownCenter.Wurp_Action(obj, activator)
  if bug_talk == 0 then
    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("By the powa of the Buggy Squad!")
    UI:SetSpeakerReverse(true)
    
    UI:SetSpeaker(dewey)
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("Uh-huh?")

    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("We will conquer da world, and then captuwe everyone's hearts!")
    
    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("Oui, a world coup!")

    UI:SetSpeaker(snow)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("H-hey... it's Rexio...")

    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowTimedDialogue("Wexio?!", 30)
    GROUND:CharTurnToCharAnimated(snow, rexio, 4)
    GROUND:CharTurnToCharAnimated(dewey, rexio, 4)
    GROUND:CharTurnToCharAnimated(pari, rexio, 4)
    COMMON.FaceEachother("Wurp", "PLAYER")
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("What awe youuuuuuuuu doing here?")

    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowTimedDialogue("Yeah, Wexio-")
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowTimedDialogue("Er, I mean...")
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("[speed=10]Yeah, Rexio![speed=1.0] What are youuuuuu doing here?")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue("Doin' chooooooores.")

    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Ha![pause=25] Y[emote=Determined]ou'we doing da mowtals work.")
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue("The Buggy Wegion would neva fall so low...")

    GROUND:CharTurnToCharAnimated(dewey, wurp, 4)
    UI:SetSpeaker(dewey)
    UI:SetSpeakerEmotion("Stunned")
    UI:WaitShowDialogue("Aren't you supposed to be getting leaves for your mom?")

    GROUND:CharTurnToCharAnimated(wurp, dewey, 4)
    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Iwewevant!")

    UI:SetSpeaker(rexio)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Ha!")
    bug_talk = 1
  else
    UI:SetSpeaker(wurp)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue("Just you wait, bugs will be the best type eveh!")
  end
end

function EntohTownCenter.Dewey_Action(obj, activator)
  if bug_talk == 0 then
    EntohTownCenter.Wurp_Action()
  else
    GROUND:CharTurnToCharAnimated(dewey, rexio, 4)
    UI:SetSpeaker(dewey)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Nice seeing you, Rexio.")
  end
end

function EntohTownCenter.Snow_Action(obj, activator)
  if bug_talk == 0 then
    EntohTownCenter.Wurp_Action()
  else
    GROUND:CharTurnToCharAnimated(snow, rexio, 4)
    UI:SetSpeaker(snow)
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue("D-don't mind him, Rexio.")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue("E-ever since he beat some... goopy thing in a dungeon, he's been...")
    GROUND:CharTurnToCharAnimated(snow, wurp, 4)
    UI:WaitShowDialogue("...acting strange.")
  end
end

function EntohTownCenter.Pari_Action(obj, activator)
  if bug_talk == 0 then
    EntohTownCenter.Wurp_Action()
  else
    GROUND:CharTurnToCharAnimated(pari, rexio, 4)
    UI:SetSpeaker(pari)
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue("Do not get in our way, Monsieur Rexi. Ze world will be ours!")
  end
end

function EntohTownCenter.Entoh_NorthEnter_Touch(obj, activator)
  print("Exiting?")
  GAME:FadeOut(false, 10)
  GAME:EnterGroundMap("EntohTownNorth", "EnterMark_South")
end

function EntohTownCenter.WaterHole_Action(obj, activator)
  local rexio = CH("PLAYER")
  UI:SetSpeaker(rexio)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(It's weird...)")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(Every time I look at this water hole, I want to say something funny about it.)")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(But I just can't up with anything...)")
end

function EntohTownCenter.Gran_Action(obj, activator)
  local gran = CH("Gran")
  UI:SetSpeaker(gran)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("[speed=0.6]Ahh, a spry young fella. I remember when I was your age...")
  UI:WaitShowDialogue("[speed=0.6]This place was full of mountains and rocks. [pause=75]F[emote=Worried]rankly dangerous to walk on for a while...")
end

function EntohTownCenter.Tidy_Action(obj, activator)
  
end

return EntohTownCenter

